export interface Tutor {
  id: number;
  name: string;
  subject: string;
  grade: string;
  rating: number;
  reviews: number;
  experience: string;
  bio: string;
  rate: string;
  image: string;
  tags: string[];
  accent: string;
  education: string;
  successRate: string;
  availability: string;
  responseTime: string;
  methodology: string;
  curriculum: "IB" | "IGCSE" | "Both";
}

export const allTutors: Tutor[] = [
  {
    id: 1,
    name: "Dr. Sarah M.",
    subject: "Mathematics",
    grade: "Year 12-13 (IB DP)",
    rating: 5.0,
    reviews: 142,
    experience: "8 Yrs",
    bio: "Oxford alumni with a PhD in Mathematics. Specialized in IB Math HL and SAT preparation with over 8 years of global tutoring experience. Known for breaking down complex calculus concepts into intuitive visual models.",
    rate: "$85/hr",
    image: "/tutor_sarah_avatar_1775559612425.png",
    tags: ["Examiner", "Oxford Alumni", "PhD holder"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "PhD in Mathematics, University of Oxford",
    successRate: "99%",
    availability: "Limited (4 slots left)",
    responseTime: "< 5 mins",
    methodology: "Rigorous exam-centric preparation combined with intuitive concept visualization.",
    curriculum: "IB",
  },
  {
    id: 2,
    name: "James R.",
    subject: "Physics",
    grade: "Year 10-11 (IGCSE)",
    rating: 4.9,
    reviews: 89,
    experience: "5 Yrs",
    bio: "Former lead physics teacher at a top international school. James focuses on kinesthetic learning and interactive simulations. Expert in IGCSE/A-Level mechanics and thermodynamics.",
    rate: "$65/hr",
    image: "/tutor_james_avatar_1775559651647.png",
    tags: ["Interactive", "Fast Replies", "Lead Teacher"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.Sc. in Physics, Imperial College London",
    successRate: "96%",
    availability: "Flexible (10+ slots)",
    responseTime: "< 15 mins",
    methodology: "Kinesthetic learning and interactive simulations for deep conceptual understanding.",
    curriculum: "IGCSE",
  },
  {
    id: 3,
    name: "Elena K.",
    subject: "Economics",
    grade: "Year 12-13 (IB DP)",
    rating: 5.0,
    reviews: 210,
    experience: "12 Yrs",
    bio: "LSE Graduate with extensive experience in international trade and macroeconomics. Elena has helped hundreds of students achieve a 7 in IB Economics through structured essay planning and case study analysis.",
    rate: "$95/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["High Success Rate", "LSE Alumni", "Essay Expert"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in Economics, London School of Economics",
    successRate: "98%",
    availability: "Very Limited (2 slots)",
    responseTime: "< 2 mins",
    methodology: "Structured essay planning and real-world case study analysis to master IB criteria.",
    curriculum: "IB",
  },
  {
    id: 4,
    name: "Daniel K.",
    subject: "Mathematics",
    grade: "Year 7-9 (MYP)",
    rating: 4.8,
    reviews: 56,
    experience: "4 Yrs",
    bio: "Math expert who makes numbers fun. Daniel uses gamified learning techniques to help middle-school students master foundations and prepare for IGCSE/MYP exams.",
    rate: "$55/hr",
    image: "/tutor_sarah_avatar_1775559612425.png",
    tags: ["Math Expert", "MYP Specialist"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "B.Sc. in Math Education, NYU",
    successRate: "94%",
    availability: "Moderate (6 slots)",
    responseTime: "< 30 mins",
    methodology: "Gamified learning techniques to make foundational math foundations engaging and accessible.",
    curriculum: "IB",
  },
  {
    id: 5,
    name: "Sophia L.",
    subject: "English Literature",
    grade: "Year 12-13 (IB DP)",
    rating: 4.9,
    reviews: 124,
    experience: "10 Yrs",
    bio: "Expert in IB English A Literature and Language. Sophia focuses on critical thinking and essay structure, ensuring students can articulate complex themes with clarity.",
    rate: "$75/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["IB Specialist", "Essay Coach"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.A. in English Literature, University of Cambridge",
    successRate: "97%",
    availability: "Moderate (5 slots)",
    responseTime: "< 10 mins",
    methodology: "Critical thinking and textual analysis focused on articulation and essay structuring.",
    curriculum: "IB",
  },
  {
    id: 6,
    name: "Aditya S.",
    subject: "Physics",
    grade: "Year 10-11 (IGCSE)",
    rating: 4.9,
    reviews: 89,
    experience: "5 Yrs",
    bio: "Former lead physics teacher at a top international school. Aditya focuses on kinesthetic learning and interactive simulations. Expert in IGCSE/A-Level mechanics and thermodynamics.",
    rate: "$65/hr",
    image: "",
    tags: ["Interactive", "Fast Replies", "Lead Teacher"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.Sc. in Physics, Imperial College London",
    successRate: "96%",
    availability: "Flexible (10+ slots)",
    responseTime: "< 15 mins",
    methodology: "Kinesthetic learning and interactive simulations for deep conceptual understanding.",
    curriculum: "IGCSE",
  },
  {
    id: 7,
    name: "Ram K.",
    subject: "Physics",
    grade: "Year 10-11 (IGCSE)",
    rating: 4.9,
    reviews: 89,
    experience: "5 Yrs",
    bio: "Former lead physics teacher at a top international school. Ram focuses on kinesthetic learning and interactive simulations. Expert in IGCSE/A-Level mechanics and thermodynamics.",
    rate: "$65/hr",
    image: "",
    tags: ["Interactive", "Fast Replies", "Lead Teacher"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.Sc. in Physics, Imperial College London",
    successRate: "96%",
    availability: "Flexible (10+ slots)",
    responseTime: "< 15 mins",
    methodology: "Kinesthetic learning and interactive simulations for deep conceptual understanding.",
    curriculum: "IGCSE",
  },
  {
    id: 8101,
    name: "Dr. Sarah M.",
    subject: "Mathematics",
    grade: "IB DP AA/AI",
    rating: 5.0,
    reviews: 142,
    experience: "8 Yrs",
    bio: "Oxford alumni with a PhD in Mathematics. Specialized in IB Math AA HL and AI HL with deep experience in calculus, statistics, and exam strategy.",
    rate: "$85/hr",
    image: "/tutor_sarah_avatar_1775559612425.png",
    tags: ["Examiner", "Oxford Alumni", "PhD Holder"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "PhD in Mathematics, University of Oxford",
    successRate: "99%",
    availability: "Limited (4 slots left)",
    responseTime: "< 5 mins",
    methodology: "Rigorous exam-centric preparation combined with intuitive concept visualization for AA and AI pathways.",
    curriculum: "IB",
  },
  {
    id: 8102,
    name: "Aarav K.",
    subject: "Mathematics",
    grade: "IB MYP / DP",
    rating: 4.9,
    reviews: 96,
    experience: "6 Yrs",
    bio: "Known for clear concept breakdowns across algebra, functions, and probability. Aarav helps students bridge MYP foundations into advanced DP-level performance.",
    rate: "$68/hr",
    image: "",
    tags: ["Concept Clarity", "AA Specialist", "Fast Replies"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "B.Sc. in Applied Mathematics, University of Warwick",
    successRate: "95%",
    availability: "Moderate (6 slots)",
    responseTime: "< 20 mins",
    methodology: "Stepwise concept-building with targeted review cycles and exam-style reinforcement.",
    curriculum: "IB",
  },
  {
    id: 8103,
    name: "Maya R.",
    subject: "Mathematics",
    grade: "IB DP AI",
    rating: 4.9,
    reviews: 88,
    experience: "5 Yrs",
    bio: "Focused on AI pathways, internal assessment planning, and question pattern recognition. Maya keeps sessions structured and highly exam-relevant.",
    rate: "$64/hr",
    image: "",
    tags: ["IA Support", "AI Focused", "Interactive"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.Sc. in Statistics, University of Manchester",
    successRate: "94%",
    availability: "Flexible (8 slots)",
    responseTime: "< 25 mins",
    methodology: "Application-first teaching with data interpretation practice and IA coaching.",
    curriculum: "IB",
  },
  {
    id: 8201,
    name: "James R.",
    subject: "Physics",
    grade: "IB DP Physics",
    rating: 4.9,
    reviews: 89,
    experience: "5 Yrs",
    bio: "Former lead physics teacher specializing in mechanics, electricity, and data analysis. Strong fit for IB students who need structure and confidence under timed conditions.",
    rate: "$65/hr",
    image: "/tutor_james_avatar_1775559651647.png",
    tags: ["Interactive", "Fast Replies", "Lead Teacher"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.Sc. in Physics, Imperial College London",
    successRate: "96%",
    availability: "Flexible (10+ slots)",
    responseTime: "< 15 mins",
    methodology: "Kinesthetic learning and interactive simulations for strong conceptual retention.",
    curriculum: "IB",
  },
  {
    id: 8202,
    name: "Nikita S.",
    subject: "Chemistry",
    grade: "IB DP Chemistry",
    rating: 4.9,
    reviews: 104,
    experience: "7 Yrs",
    bio: "Nikita simplifies organic chemistry, stoichiometry, and data-based questions with a very systematic approach tailored for IB marking criteria.",
    rate: "$72/hr",
    image: "",
    tags: ["HL Support", "Practical Skills", "Exam Focused"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.Sc. in Chemistry, University of Bristol",
    successRate: "97%",
    availability: "Moderate (5 slots)",
    responseTime: "< 18 mins",
    methodology: "Structured problem decomposition paired with criterion-driven lab and paper practice.",
    curriculum: "IB",
  },
  {
    id: 8203,
    name: "Rohan P.",
    subject: "Biology",
    grade: "IB DP Biology",
    rating: 4.8,
    reviews: 78,
    experience: "5 Yrs",
    bio: "Helps students master application-style biology questions, command terms, and structured extended responses across core and HL topics.",
    rate: "$63/hr",
    image: "",
    tags: ["Data Analysis", "HL Biology", "Patient"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.Sc. in Molecular Biology, University of Edinburgh",
    successRate: "95%",
    availability: "Flexible (7 slots)",
    responseTime: "< 22 mins",
    methodology: "Concept mapping, command-term drilling, and markscheme-led answer training.",
    curriculum: "IB",
  },
  {
    id: 8301,
    name: "Elena K.",
    subject: "Economics",
    grade: "IB DP Economics",
    rating: 5.0,
    reviews: 210,
    experience: "12 Yrs",
    bio: "LSE graduate with deep experience in macroeconomics, essay planning, and case-study interpretation. Elena is especially strong with 15-mark and 10-mark structure.",
    rate: "$95/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["High Success Rate", "LSE Alumni", "Essay Expert"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in Economics, London School of Economics",
    successRate: "98%",
    availability: "Very Limited (2 slots)",
    responseTime: "< 2 mins",
    methodology: "Structured essay planning and real-world case study analysis to master IB criteria.",
    curriculum: "IB",
  },
  {
    id: 8302,
    name: "Kabir N.",
    subject: "Business Management",
    grade: "IB DP Business",
    rating: 4.9,
    reviews: 91,
    experience: "6 Yrs",
    bio: "Kabir focuses on structure, case analysis, and application-heavy responses for Business Management students preparing for both internal and external assessment.",
    rate: "$69/hr",
    image: "",
    tags: ["Case Analysis", "IA Support", "Exam Focused"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "MBA, University of Bath",
    successRate: "95%",
    availability: "Moderate (6 slots)",
    responseTime: "< 20 mins",
    methodology: "Case-based teaching with criterion-focused writing and decision-making drills.",
    curriculum: "IB",
  },
  {
    id: 8303,
    name: "Hana T.",
    subject: "History",
    grade: "IB DP History",
    rating: 4.8,
    reviews: 73,
    experience: "5 Yrs",
    bio: "Hana helps with source work, essay framing, and evidence recall across modern history units with a calm, highly structured lesson style.",
    rate: "$62/hr",
    image: "",
    tags: ["Essay Coach", "Source Work", "Structured"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in Modern History, King's College London",
    successRate: "94%",
    availability: "Flexible (7 slots)",
    responseTime: "< 25 mins",
    methodology: "Source evaluation drills, essay planning frameworks, and recall systems for paper confidence.",
    curriculum: "IB",
  },
  {
    id: 8401,
    name: "Sophia L.",
    subject: "English Literature",
    grade: "IB DP English A",
    rating: 4.9,
    reviews: 124,
    experience: "10 Yrs",
    bio: "Expert in IB English A Literature and Language. Sophia focuses on critical thinking, literary analysis, and strong essay structure for higher scoring responses.",
    rate: "$75/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["IB Specialist", "Essay Coach", "Close Reading"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.A. in English Literature, University of Cambridge",
    successRate: "97%",
    availability: "Moderate (5 slots)",
    responseTime: "< 10 mins",
    methodology: "Critical thinking and textual analysis focused on articulation and essay structuring.",
    curriculum: "IB",
  },
  {
    id: 8402,
    name: "Ritika P.",
    subject: "English Language",
    grade: "IB MYP / DP",
    rating: 4.8,
    reviews: 82,
    experience: "6 Yrs",
    bio: "Ritika supports commentary writing, thesis building, and timed analysis practice with a clear focus on language precision and interpretation.",
    rate: "$61/hr",
    image: "",
    tags: ["Language Analysis", "Clear Feedback", "Exam Ready"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in English Studies, University of Leeds",
    successRate: "95%",
    availability: "Flexible (8 slots)",
    responseTime: "< 20 mins",
    methodology: "Sentence-level feedback, commentary structure, and timed response refinement.",
    curriculum: "IB",
  },
  {
    id: 8403,
    name: "Oliver D.",
    subject: "English Literature",
    grade: "IB DP English HL",
    rating: 4.9,
    reviews: 77,
    experience: "5 Yrs",
    bio: "Oliver specializes in Paper 1 and Paper 2 preparation, helping students turn ideas into precise, criterion-aware essays with strong textual support.",
    rate: "$66/hr",
    image: "",
    tags: ["Paper 1", "Paper 2", "Textual Analysis"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.A. in Comparative Literature, Durham University",
    successRate: "95%",
    availability: "Moderate (6 slots)",
    responseTime: "< 18 mins",
    methodology: "Paper-specific practice with close reading, annotation, and argument development.",
    curriculum: "IB",
  },
  {
    id: 8501,
    name: "Lucia M.",
    subject: "Spanish",
    grade: "IB Language B",
    rating: 4.9,
    reviews: 86,
    experience: "6 Yrs",
    bio: "Lucia builds fluency, writing control, and oral confidence for IB Spanish students with a strong focus on practical exam application.",
    rate: "$64/hr",
    image: "",
    tags: ["Oral Prep", "Writing Skills", "Interactive"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in Hispanic Studies, University of Barcelona",
    successRate: "95%",
    availability: "Flexible (8 slots)",
    responseTime: "< 18 mins",
    methodology: "Speaking drills, guided writing, and comprehension routines tailored for IB performance.",
    curriculum: "IB",
  },
  {
    id: 8502,
    name: "Amelie R.",
    subject: "French",
    grade: "IB Language B",
    rating: 4.8,
    reviews: 71,
    experience: "5 Yrs",
    bio: "Amelie helps students improve written accuracy, comprehension, and speaking performance with highly practical exam-style routines.",
    rate: "$60/hr",
    image: "",
    tags: ["Speaking Focus", "Grammar Support", "Patient"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    education: "M.A. in French Language Teaching, Sorbonne University",
    successRate: "94%",
    availability: "Moderate (7 slots)",
    responseTime: "< 22 mins",
    methodology: "Grammar correction, oral rehearsal, and comprehension pattern training for balanced fluency.",
    curriculum: "IB",
  },
  {
    id: 8503,
    name: "Layla H.",
    subject: "Arabic",
    grade: "IB Language A/B",
    rating: 4.9,
    reviews: 67,
    experience: "5 Yrs",
    bio: "Layla focuses on expression, grammar accuracy, and reading interpretation with a balanced approach to both classroom and exam performance.",
    rate: "$62/hr",
    image: "",
    tags: ["Expression", "Reading Skills", "Fast Replies"],
    accent: "bg-primary/10 text-primary border-primary/20",
    education: "M.A. in Arabic Studies, SOAS University of London",
    successRate: "94%",
    availability: "Flexible (7 slots)",
    responseTime: "< 20 mins",
    methodology: "Balanced reading, writing, and expression routines with exam-focused reinforcement.",
    curriculum: "IB",
  }
];
