import type { SeoGeneratorInput } from "./types";

export const GENERATED_PAGE_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["page"],
  properties: {
    page: {
      type: "object",
      additionalProperties: false,
      required: [
        "pageId",
        "pageType",
        "status",
        "indexFlag",
        "canonicalUrl",
        "slug",
        "cityName",
        "citySlug",
        "primaryKeyword",
        "secondaryKeywords",
        "serviceFocus",
        "programmes",
        "subjects",
        "tutoringModes",
        "premiumAreas",
        "nearbyAreas",
        "nearbyCities",
        "schoolsMentioned",
        "metaTitle",
        "metaDescription",
        "ogTitle",
        "ogDescription",
        "ogImage",
        "twitterTitle",
        "twitterDescription",
        "breadcrumbTitle",
        "h1",
        "heroTitle",
        "heroSubtitle",
        "introSummary",
        "contentBlocks",
        "faqs",
        "internalLinks",
        "relatedPageSuggestions",
        "schema",
        "quality",
        "finalCta",
        "lastUpdated",
      ],
      properties: {
        pageId: { type: "string" },
        pageType: { type: "string", enum: ["city", "area", "sector", "society", "school", "subject", "programme"] },
        status: { type: "string", enum: ["draft", "review", "published", "paused"] },
        indexFlag: { type: "string", enum: ["index", "noindex"] },
        canonicalUrl: { type: "string" },
        canonicalTarget: { type: "string" },
        slug: { type: "string" },
        cityName: { type: "string" },
        citySlug: { type: "string" },
        parentLocation: { type: "string" },
        microLocationName: { type: "string" },
        microLocationType: { type: "string", enum: ["area", "sector", "society", "school"] },
        primaryKeyword: { type: "string" },
        secondaryKeywords: { type: "array", items: { type: "string" } },
        serviceFocus: { type: "string" },
        programmes: { type: "array", items: { type: "string", enum: ["PYP", "MYP", "DP"] } },
        subjects: { type: "array", items: { type: "string" } },
        tutoringModes: { type: "array", items: { type: "string", enum: ["home", "online", "hybrid"] } },
        premiumAreas: { type: "array", items: { type: "string" } },
        nearbyAreas: { type: "array", items: { type: "string" } },
        nearbyCities: { type: "array", items: { type: "string" } },
        schoolsMentioned: { type: "array", items: { type: "string" } },
        metaTitle: { type: "string" },
        metaDescription: { type: "string" },
        ogTitle: { type: "string" },
        ogDescription: { type: "string" },
        ogImage: { type: "string" },
        twitterTitle: { type: "string" },
        twitterDescription: { type: "string" },
        breadcrumbTitle: { type: "string" },
        h1: { type: "string" },
        heroTitle: { type: "string" },
        heroSubtitle: { type: "string" },
        introSummary: { type: "string" },
        contentBlocks: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["type", "heading", "body", "items"],
            properties: {
              type: { type: "string", enum: ["intro", "programmes", "subjects", "local_areas", "schools", "matching_process", "verification", "tutoring_modes", "trust", "cta"] },
              heading: { type: "string" },
              body: { type: "string" },
              items: { type: "array", items: { type: "string" } },
            },
          },
        },
        faqs: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: ["question", "answer"],
            properties: { question: { type: "string" }, answer: { type: "string" } },
          },
        },
        internalLinks: { type: "array", items: { "$ref": "#/$defs/internalLink" } },
        relatedPageSuggestions: { type: "array", items: { "$ref": "#/$defs/internalLink" } },
        schema: { type: "object", additionalProperties: true },
        quality: {
          type: "object",
          additionalProperties: false,
          required: ["wordCount", "uniquenessScore", "localDepthScore", "seoScore", "readabilityScore", "internalLinkScore", "duplicateRisk", "recommendedIndexFlag", "warnings"],
          properties: {
            wordCount: { type: "number" },
            uniquenessScore: { type: "number" },
            localDepthScore: { type: "number" },
            seoScore: { type: "number" },
            readabilityScore: { type: "number" },
            internalLinkScore: { type: "number" },
            duplicateRisk: { type: "string", enum: ["low", "medium", "high"] },
            recommendedIndexFlag: { type: "string", enum: ["index", "noindex"] },
            warnings: { type: "array", items: { type: "string" } },
          },
        },
        finalCta: { type: "string" },
        schoolDisclaimer: { type: "string" },
        lastUpdated: { type: "string" },
      },
    },
  },
  $defs: {
    internalLink: {
      type: "object",
      additionalProperties: false,
      required: ["linkId", "sourcePageId", "targetPageId", "targetUrl", "anchorText", "linkContext", "linkType", "priority", "followStatus", "isCrawlable", "linkStatus"],
      properties: {
        linkId: { type: "string" },
        sourcePageId: { type: "string" },
        targetPageId: { type: "string" },
        targetUrl: { type: "string" },
        anchorText: { type: "string" },
        linkContext: { type: "string" },
        linkType: { type: "string", enum: ["breadcrumb", "contextual", "card", "footer", "related", "cta"] },
        priority: { type: "string", enum: ["high", "medium", "low"] },
        followStatus: { type: "string", enum: ["follow", "nofollow"] },
        isCrawlable: { type: "boolean" },
        linkStatus: { type: "string", enum: ["active", "broken", "redirect"] },
      },
    },
  },
} as const;

export function buildSeoGeneratorSystemPrompt(): string {
  return [
    "You are an expert SEO content strategist for premium IB tutoring pages for IB Gram.",
    "Return structured JSON only. Do not return markdown, HTML, comments, or prose outside JSON.",
    "Write parent-facing, natural, plagiarism-free, grammar-checked content that avoids keyword stuffing and fake claims.",
    "Create useful local pages, not doorway pages. If local depth is weak, recommend noindex in JSON warnings.",
    "Do not imply school partnerships. For school pages, include: IB Gram is an independent tutoring platform and is not officially affiliated with this school unless specifically stated.",
    "Visible content for indexable pages should naturally support about 1600-2000 words across blocks and FAQs.",
    "Use safe language for societies and residential communities. Do not invent building facts.",
    "Avoid guarantees. Tutors may support IA, EE and exam preparation, but must not write assessed work.",
  ].join("\n");
}

export function buildSeoGeneratorUserPrompt(input: SeoGeneratorInput, canonicalUrl: string, pageId: string): string {
  return JSON.stringify({
    task: "Generate one complete IB Gram SEO page draft as structured JSON.",
    requiredCanonicalUrl: canonicalUrl,
    requiredPageId: pageId,
    currentDate: new Date().toISOString().slice(0, 10),
    input,
    contentBlocksRequired: [
      "intro",
      "programmes",
      "subjects",
      "local_areas",
      "schools",
      "matching_process",
      "tutoring_modes",
      "verification",
      "trust",
      "cta",
    ],
  });
}
