import type { IgcseSubjectCatalogEntry, IgcseSubjectGroupKey } from "./types";

/**
 * The 53 IGCSE subject hub pages served at /igcse/subject/<slug>/.
 * Syllabus codes are the Cambridge codes already listed in the IGCSE subject
 * directory, so the hub pages and the on-site directory never disagree.
 */
export const IGCSE_SUBJECT_GROUP_LABELS: Record<IgcseSubjectGroupKey, string> = {
  "english-and-languages": "English & Languages",
  "mathematics": "Mathematics",
  "sciences": "Sciences",
  "business-and-economics": "Business & Economics",
  "humanities": "Humanities & Social Sciences",
  "computer-and-technology": "Computer & Technology",
  "arts-and-creative": "Arts & Creative Subjects",
  "physical-and-other": "Physical & Other Subjects",
};

export const igcseSubjectCatalog: IgcseSubjectCatalogEntry[] = [
  // ── English & Languages ──
  {
    slug: "english",
    label: "English — First Language",
    shortLabel: "English",
    group: "english-and-languages",
    // 0510/0511/0991/0993 are the English as a Second Language codes and belong
    // to that entry, not here — the site's subject directory had them filed under
    // the general "English" heading.
    codes: ["0427", "0476", "0477", "0486", "0500", "0522", "0524", "0526", "0627", "0772", "0990", "0475", "0472", "0992"],
    tutorTags: ["English", "English — First Language"],
    siblings: ["english-as-a-second-language", "world-literature", "spanish-literature", "french", "spanish"],
  },
  {
    slug: "english-as-a-second-language",
    label: "English as a Second Language",
    shortLabel: "English (Second Language)",
    group: "english-and-languages",
    // Verified against Cambridge: 0510 (speaking endorsement) and 0511 (count-in
    // speaking), with 0993/0991 the 9-1 graded equivalents. The site's subject
    // directory listed 0485, which is not a current Cambridge ESL code.
    codes: ["0510", "0511", "0993", "0991"],
    tutorTags: ["English (Second Language)", "English as a Second Language", "English (as a Second Language)"],
    siblings: ["english", "world-literature", "spanish-literature", "french", "spanish"],
  },
  {
    slug: "world-literature",
    label: "World Literature",
    shortLabel: "World Literature",
    group: "english-and-languages",
    codes: ["0408"],
    tutorTags: ["World Literature"],
    siblings: ["english", "english-as-a-second-language", "spanish-literature", "french", "spanish"],
  },
  {
    slug: "spanish-literature",
    label: "Spanish Literature",
    shortLabel: "Spanish Literature",
    group: "english-and-languages",
    codes: ["0488"],
    tutorTags: ["Spanish Literature"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "french", "spanish"],
  },
  {
    slug: "french",
    label: "French",
    shortLabel: "French",
    group: "english-and-languages",
    codes: ["0501", "0520", "0528", "0685", "7156"],
    tutorTags: ["French"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "spanish"],
  },
  {
    slug: "spanish",
    label: "Spanish",
    shortLabel: "Spanish",
    group: "english-and-languages",
    codes: ["0474", "0502", "0530", "0533", "0537", "0678", "7160"],
    tutorTags: ["Spanish"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "german",
    label: "German",
    shortLabel: "German",
    group: "english-and-languages",
    codes: ["0505", "0525", "0529", "0677", "7159"],
    tutorTags: ["German"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "italian",
    label: "Italian",
    shortLabel: "Italian",
    group: "english-and-languages",
    codes: ["0535", "7164"],
    tutorTags: ["Italian"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "chinese",
    label: "Chinese",
    shortLabel: "Chinese",
    group: "english-and-languages",
    codes: ["0509", "0523", "0534", "0547"],
    tutorTags: ["Chinese"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "arabic",
    label: "Arabic",
    shortLabel: "Arabic",
    group: "english-and-languages",
    codes: ["0508", "0527", "0544", "7180", "7184"],
    tutorTags: ["Arabic"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "hindi",
    label: "Hindi",
    shortLabel: "Hindi",
    group: "english-and-languages",
    codes: ["0549"],
    tutorTags: ["Hindi"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "urdu",
    label: "Urdu",
    shortLabel: "Urdu",
    group: "english-and-languages",
    codes: ["0539"],
    tutorTags: ["Urdu"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "japanese",
    label: "Japanese",
    shortLabel: "Japanese",
    group: "english-and-languages",
    codes: ["0507", "0519"],
    tutorTags: ["Japanese"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "portuguese",
    label: "Portuguese",
    shortLabel: "Portuguese",
    group: "english-and-languages",
    codes: ["0504", "0540"],
    tutorTags: ["Portuguese"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "malay",
    label: "Malay",
    shortLabel: "Malay",
    group: "english-and-languages",
    codes: ["0546", "0696"],
    tutorTags: ["Malay"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "indonesian",
    label: "Indonesian",
    shortLabel: "Indonesian",
    group: "english-and-languages",
    codes: ["0545"],
    tutorTags: ["Indonesian"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "russian",
    label: "Russian",
    shortLabel: "Russian",
    group: "english-and-languages",
    codes: ["0516"],
    tutorTags: ["Russian"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "korean",
    label: "Korean",
    shortLabel: "Korean",
    group: "english-and-languages",
    codes: ["0521"],
    tutorTags: ["Korean"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "latin",
    label: "Latin",
    shortLabel: "Latin",
    group: "english-and-languages",
    codes: ["0480"],
    tutorTags: ["Latin"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "swahili",
    label: "Swahili",
    shortLabel: "Swahili",
    group: "english-and-languages",
    codes: ["0262"],
    tutorTags: ["Swahili"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "thai",
    label: "Thai",
    shortLabel: "Thai",
    group: "english-and-languages",
    codes: ["0518"],
    tutorTags: ["Thai"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "turkish",
    label: "Turkish",
    shortLabel: "Turkish",
    group: "english-and-languages",
    codes: ["0513"],
    tutorTags: ["Turkish"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  {
    slug: "vietnamese",
    label: "Vietnamese",
    shortLabel: "Vietnamese",
    group: "english-and-languages",
    codes: ["0695"],
    tutorTags: ["Vietnamese"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  // ── Mathematics ──
  {
    slug: "mathematics",
    label: "Mathematics",
    shortLabel: "Mathematics",
    group: "mathematics",
    codes: ["0444", "0459", "0580", "0581", "0606", "0607", "0626", "0980"],
    tutorTags: ["Mathematics"],
    siblings: ["english", "english-as-a-second-language", "world-literature", "spanish-literature", "french"],
  },
  // ── Sciences ──
  {
    slug: "biology",
    label: "Biology",
    shortLabel: "Biology",
    group: "sciences",
    codes: ["0438", "0610", "0970"],
    tutorTags: ["Biology"],
    siblings: ["chemistry", "physics", "science", "sciences", "physical-science"],
  },
  {
    slug: "chemistry",
    label: "Chemistry",
    shortLabel: "Chemistry",
    group: "sciences",
    codes: ["0439", "0620", "0971"],
    tutorTags: ["Chemistry"],
    siblings: ["biology", "physics", "science", "sciences", "physical-science"],
  },
  {
    slug: "physics",
    label: "Physics",
    shortLabel: "Physics",
    group: "sciences",
    codes: ["0443", "0625", "0972"],
    tutorTags: ["Physics"],
    siblings: ["biology", "chemistry", "science", "sciences", "physical-science"],
  },
  {
    slug: "science",
    label: "Combined Science",
    shortLabel: "Combined Science",
    group: "sciences",
    codes: ["0653"],
    tutorTags: ["Combined Science", "Science"],
    siblings: ["biology", "chemistry", "physics", "sciences", "physical-science"],
  },
  {
    slug: "sciences",
    label: "Co-ordinated Sciences",
    shortLabel: "Co-ordinated Sciences",
    group: "sciences",
    codes: ["0442", "0654", "0973"],
    tutorTags: ["Co-ordinated Sciences", "Sciences"],
    siblings: ["biology", "chemistry", "physics", "science", "physical-science"],
  },
  {
    slug: "physical-science",
    label: "Physical Science",
    shortLabel: "Physical Science",
    group: "sciences",
    codes: ["0652"],
    tutorTags: ["Physical Science"],
    siblings: ["biology", "chemistry", "physics", "science", "sciences"],
  },
  {
    slug: "environmental-management",
    label: "Environmental Management",
    shortLabel: "Environmental Management",
    group: "sciences",
    codes: ["0680"],
    tutorTags: ["Environmental Management"],
    siblings: ["biology", "chemistry", "physics", "science", "sciences"],
  },
  {
    slug: "marine-science",
    label: "Marine Science",
    shortLabel: "Marine Science",
    group: "sciences",
    codes: ["0697"],
    tutorTags: ["Marine Science"],
    siblings: ["biology", "chemistry", "physics", "science", "sciences"],
  },
  // ── Business & Economics ──
  {
    slug: "accounting",
    label: "Accounting",
    shortLabel: "Accounting",
    group: "business-and-economics",
    codes: ["0452", "0985"],
    tutorTags: ["Accounting"],
    siblings: ["business-studies", "economics", "enterprise", "english", "english-as-a-second-language"],
  },
  {
    slug: "business-studies",
    label: "Business Studies",
    shortLabel: "Business Studies",
    group: "business-and-economics",
    codes: ["0450", "0986"],
    tutorTags: ["Business Studies"],
    siblings: ["accounting", "economics", "enterprise", "english", "english-as-a-second-language"],
  },
  {
    slug: "economics",
    label: "Economics",
    shortLabel: "Economics",
    group: "business-and-economics",
    codes: ["0437", "0455", "0987"],
    tutorTags: ["Economics"],
    siblings: ["accounting", "business-studies", "enterprise", "english", "english-as-a-second-language"],
  },
  {
    slug: "enterprise",
    label: "Enterprise",
    shortLabel: "Enterprise",
    group: "business-and-economics",
    codes: ["0454"],
    tutorTags: ["Enterprise"],
    siblings: ["accounting", "business-studies", "economics", "english", "english-as-a-second-language"],
  },
  // ── Humanities & Social Sciences ──
  {
    slug: "geography",
    label: "Geography",
    shortLabel: "Geography",
    group: "humanities",
    codes: ["0460", "0976"],
    tutorTags: ["Geography"],
    siblings: ["history", "global-perspectives", "sociology", "religious-studies", "travel-and-tourism"],
  },
  {
    slug: "history",
    label: "History",
    shortLabel: "History",
    group: "humanities",
    codes: ["0416", "0470", "0977", "0409"],
    tutorTags: ["History"],
    siblings: ["geography", "global-perspectives", "sociology", "religious-studies", "travel-and-tourism"],
  },
  {
    slug: "global-perspectives",
    label: "Global Perspectives",
    shortLabel: "Global Perspectives",
    group: "humanities",
    codes: ["0426", "0457"],
    tutorTags: ["Global Perspectives"],
    siblings: ["geography", "history", "sociology", "religious-studies", "travel-and-tourism"],
  },
  {
    slug: "sociology",
    label: "Sociology",
    shortLabel: "Sociology",
    group: "humanities",
    codes: ["0495"],
    tutorTags: ["Sociology"],
    siblings: ["geography", "history", "global-perspectives", "religious-studies", "travel-and-tourism"],
  },
  {
    slug: "religious-studies",
    label: "Religious Studies",
    shortLabel: "Religious Studies",
    group: "humanities",
    codes: ["0490"],
    tutorTags: ["Religious Studies"],
    siblings: ["geography", "history", "global-perspectives", "sociology", "travel-and-tourism"],
  },
  {
    slug: "travel-and-tourism",
    label: "Travel and Tourism",
    shortLabel: "Travel and Tourism",
    group: "humanities",
    codes: ["0471"],
    tutorTags: ["Travel and Tourism"],
    siblings: ["geography", "history", "global-perspectives", "sociology", "religious-studies"],
  },
  {
    slug: "development-studies",
    label: "Development Studies",
    shortLabel: "Development Studies",
    group: "humanities",
    codes: ["0453"],
    tutorTags: ["Development Studies"],
    siblings: ["geography", "history", "global-perspectives", "sociology", "religious-studies"],
  },
  // ── Computer & Technology ──
  {
    slug: "computer-science",
    label: "Computer Science",
    shortLabel: "Computer Science",
    group: "computer-and-technology",
    codes: ["0478", "0984"],
    tutorTags: ["Computer Science"],
    siblings: ["computer-studies", "ict", "design-and-technology", "english", "english-as-a-second-language"],
  },
  {
    slug: "computer-studies",
    label: "Computer Studies",
    shortLabel: "Computer Studies",
    group: "computer-and-technology",
    codes: ["0420", "0441"],
    tutorTags: ["Computer Studies"],
    siblings: ["computer-science", "ict", "design-and-technology", "english", "english-as-a-second-language"],
  },
  {
    slug: "ict",
    label: "Information and Communication Technology (ICT)",
    shortLabel: "ICT",
    group: "computer-and-technology",
    codes: ["0417", "0983"],
    tutorTags: ["ICT", "Information and Communication Technology (ICT)"],
    siblings: ["computer-science", "computer-studies", "design-and-technology", "english", "english-as-a-second-language"],
  },
  {
    slug: "design-and-technology",
    label: "Design and Technology",
    shortLabel: "Design and Technology",
    group: "computer-and-technology",
    codes: ["0445", "0979"],
    tutorTags: ["Design and Technology"],
    siblings: ["computer-science", "computer-studies", "ict", "english", "english-as-a-second-language"],
  },
  // ── Arts & Creative Subjects ──
  {
    slug: "art-and-design",
    label: "Art and Design",
    shortLabel: "Art and Design",
    group: "arts-and-creative",
    codes: ["0400", "0415", "0989"],
    tutorTags: ["Art and Design"],
    siblings: ["drama", "music", "english", "english-as-a-second-language", "world-literature"],
  },
  {
    slug: "drama",
    label: "Drama",
    shortLabel: "Drama",
    group: "arts-and-creative",
    codes: ["0411", "0428", "0994"],
    tutorTags: ["Drama"],
    siblings: ["art-and-design", "music", "english", "english-as-a-second-language", "world-literature"],
  },
  {
    slug: "music",
    label: "Music",
    shortLabel: "Music",
    group: "arts-and-creative",
    codes: ["0410", "0429", "0978"],
    tutorTags: ["Music"],
    siblings: ["art-and-design", "drama", "english", "english-as-a-second-language", "world-literature"],
  },
  // ── Physical & Other Subjects ──
  {
    slug: "physical-education",
    label: "Physical Education",
    shortLabel: "Physical Education",
    group: "physical-and-other",
    codes: ["0413", "0995"],
    tutorTags: ["Physical Education"],
    siblings: ["child-development", "food-and-nutrition", "english", "english-as-a-second-language", "world-literature"],
  },
  {
    slug: "child-development",
    label: "Child Development",
    shortLabel: "Child Development",
    group: "physical-and-other",
    codes: ["0637"],
    tutorTags: ["Child Development"],
    siblings: ["physical-education", "food-and-nutrition", "english", "english-as-a-second-language", "world-literature"],
  },
  {
    slug: "food-and-nutrition",
    label: "Food and Nutrition",
    shortLabel: "Food and Nutrition",
    group: "physical-and-other",
    codes: ["0648"],
    tutorTags: ["Food and Nutrition"],
    siblings: ["physical-education", "child-development", "english", "english-as-a-second-language", "world-literature"],
  },
];

export const igcseSubjectSlugs: string[] = igcseSubjectCatalog.map((entry) => entry.slug);

const bySlug = new Map(igcseSubjectCatalog.map((entry) => [entry.slug, entry]));

export function getIgcseSubjectCatalogEntry(slug: string): IgcseSubjectCatalogEntry | undefined {
  return bySlug.get(slug.toLowerCase());
}
