/**
 * Generated by scripts/igcse-subjects/build-registry.ts — do not edit by hand.
 */
import type { IgcseSubjectContent } from "./types";
import { accounting } from "./subjects/accounting";
import { arabic } from "./subjects/arabic";
import { artAndDesign } from "./subjects/art-and-design";
import { biology } from "./subjects/biology";
import { businessStudies } from "./subjects/business-studies";
import { chemistry } from "./subjects/chemistry";
import { childDevelopment } from "./subjects/child-development";
import { chinese } from "./subjects/chinese";
import { computerScience } from "./subjects/computer-science";
import { computerStudies } from "./subjects/computer-studies";
import { designAndTechnology } from "./subjects/design-and-technology";
import { developmentStudies } from "./subjects/development-studies";
import { drama } from "./subjects/drama";
import { economics } from "./subjects/economics";
import { english } from "./subjects/english";
import { englishAsASecondLanguage } from "./subjects/english-as-a-second-language";
import { enterprise } from "./subjects/enterprise";
import { environmentalManagement } from "./subjects/environmental-management";
import { foodAndNutrition } from "./subjects/food-and-nutrition";
import { french } from "./subjects/french";
import { geography } from "./subjects/geography";
import { german } from "./subjects/german";
import { globalPerspectives } from "./subjects/global-perspectives";
import { hindi } from "./subjects/hindi";
import { history } from "./subjects/history";
import { ict } from "./subjects/ict";
import { indonesian } from "./subjects/indonesian";
import { italian } from "./subjects/italian";
import { japanese } from "./subjects/japanese";
import { korean } from "./subjects/korean";
import { latin } from "./subjects/latin";
import { malay } from "./subjects/malay";
import { marineScience } from "./subjects/marine-science";
import { mathematics } from "./subjects/mathematics";
import { music } from "./subjects/music";
import { physicalEducation } from "./subjects/physical-education";
import { physicalScience } from "./subjects/physical-science";
import { physics } from "./subjects/physics";
import { portuguese } from "./subjects/portuguese";
import { religiousStudies } from "./subjects/religious-studies";
import { russian } from "./subjects/russian";
import { science } from "./subjects/science";
import { sciences } from "./subjects/sciences";
import { sociology } from "./subjects/sociology";
import { spanish } from "./subjects/spanish";
import { spanishLiterature } from "./subjects/spanish-literature";
import { swahili } from "./subjects/swahili";
import { thai } from "./subjects/thai";
import { travelAndTourism } from "./subjects/travel-and-tourism";
import { turkish } from "./subjects/turkish";
import { urdu } from "./subjects/urdu";
import { vietnamese } from "./subjects/vietnamese";
import { worldLiterature } from "./subjects/world-literature";

export const igcseSubjectContents: IgcseSubjectContent[] = [
  accounting,
  arabic,
  artAndDesign,
  biology,
  businessStudies,
  chemistry,
  childDevelopment,
  chinese,
  computerScience,
  computerStudies,
  designAndTechnology,
  developmentStudies,
  drama,
  economics,
  english,
  englishAsASecondLanguage,
  enterprise,
  environmentalManagement,
  foodAndNutrition,
  french,
  geography,
  german,
  globalPerspectives,
  hindi,
  history,
  ict,
  indonesian,
  italian,
  japanese,
  korean,
  latin,
  malay,
  marineScience,
  mathematics,
  music,
  physicalEducation,
  physicalScience,
  physics,
  portuguese,
  religiousStudies,
  russian,
  science,
  sciences,
  sociology,
  spanish,
  spanishLiterature,
  swahili,
  thai,
  travelAndTourism,
  turkish,
  urdu,
  vietnamese,
  worldLiterature,
];

