import type { CourseTutorProfile } from "./course-tutor-types";

export const ibEnglishTutorData: CourseTutorProfile[] = [
  {
    id: 8401,
    name: "Sophia L.",
    subject: "English Literature",
    grade: "IB DP English A",
    rating: 4.9,
    reviews: 124,
    experience: "10 Yrs",
    bio: "Expert in IB English A Literature and Language. Sophia focuses on critical thinking, literary analysis, and strong essay structure for higher scoring responses.",
    rate: "$75/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["IB Specialist", "Essay Coach", "Close Reading"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
  {
    id: 8402,
    name: "Ritika P.",
    subject: "English Language",
    grade: "IB MYP / DP",
    rating: 4.8,
    reviews: 82,
    experience: "6 Yrs",
    bio: "Ritika supports commentary writing, thesis building, and timed analysis practice with a clear focus on language precision and interpretation.",
    rate: "$61/hr",
    image: "",
    tags: ["Language Analysis", "Clear Feedback", "Exam Ready"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
  {
    id: 8403,
    name: "Oliver D.",
    subject: "English Literature",
    grade: "IB DP English HL",
    rating: 4.9,
    reviews: 77,
    experience: "5 Yrs",
    bio: "Oliver specializes in Paper 1 and Paper 2 preparation, helping students turn ideas into precise, criterion-aware essays with strong textual support.",
    rate: "$66/hr",
    image: "",
    tags: ["Paper 1", "Paper 2", "Textual Analysis"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
];
