import type { CourseTutorProfile } from "./course-tutor-types";

export const ibIndividualsAndSocietiesTutorData: CourseTutorProfile[] = [
  {
    id: 8301,
    name: "Elena K.",
    subject: "Economics",
    grade: "IB DP Economics",
    rating: 5.0,
    reviews: 210,
    experience: "12 Yrs",
    bio: "LSE graduate with deep experience in macroeconomics, essay planning, and case-study interpretation. Elena is especially strong with 15-mark and 10-mark structure.",
    rate: "$95/hr",
    image: "/tutor_elena_avatar_1775559725738.png",
    tags: ["High Success Rate", "LSE Alumni", "Essay Expert"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
  {
    id: 8302,
    name: "Kabir N.",
    subject: "Business Management",
    grade: "IB DP Business",
    rating: 4.9,
    reviews: 91,
    experience: "6 Yrs",
    bio: "Kabir focuses on structure, case analysis, and application-heavy responses for Business Management students preparing for both internal and external assessment.",
    rate: "$69/hr",
    image: "",
    tags: ["Case Analysis", "IA Support", "Exam Focused"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
  {
    id: 8303,
    name: "Hana T.",
    subject: "History",
    grade: "IB DP History",
    rating: 4.8,
    reviews: 73,
    experience: "5 Yrs",
    bio: "Hana helps with source work, essay framing, and evidence recall across modern history units with a calm, highly structured lesson style.",
    rate: "$62/hr",
    image: "",
    tags: ["Essay Coach", "Source Work", "Structured"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
];
