import type { CourseTutorProfile } from "./course-tutor-types";

export const ibLanguageTutorData: CourseTutorProfile[] = [
  {
    id: 8501,
    name: "Lucia M.",
    subject: "Spanish",
    grade: "IB Language B",
    rating: 4.9,
    reviews: 86,
    experience: "6 Yrs",
    bio: "Lucia builds fluency, writing control, and oral confidence for IB Spanish students with a strong focus on practical exam application.",
    rate: "$64/hr",
    image: "",
    tags: ["Oral Prep", "Writing Skills", "Interactive"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
  {
    id: 8502,
    name: "Amelie R.",
    subject: "French",
    grade: "IB Language B",
    rating: 4.8,
    reviews: 71,
    experience: "5 Yrs",
    bio: "Amelie helps students improve written accuracy, comprehension, and speaking performance with highly practical exam-style routines.",
    rate: "$60/hr",
    image: "",
    tags: ["Speaking Focus", "Grammar Support", "Patient"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
  {
    id: 8503,
    name: "Layla H.",
    subject: "Arabic",
    grade: "IB Language A/B",
    rating: 4.9,
    reviews: 67,
    experience: "5 Yrs",
    bio: "Layla focuses on expression, grammar accuracy, and reading interpretation with a balanced approach to both classroom and exam performance.",
    rate: "$62/hr",
    image: "",
    tags: ["Expression", "Reading Skills", "Fast Replies"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
];
