import type { CourseTutorProfile } from "./course-tutor-types";

export const ibMathTutorData: CourseTutorProfile[] = [
  {
    id: 8101,
    name: "Dr. Sarah M.",
    subject: "Mathematics",
    grade: "IB DP AA/AI",
    rating: 5.0,
    reviews: 142,
    experience: "8 Yrs",
    bio: "Oxford alumni with a PhD in Mathematics. Specialized in IB Math AA HL and AI HL with deep experience in calculus, statistics, and exam strategy.",
    rate: "$85/hr",
    image: "/tutor_sarah_avatar_1775559612425.png",
    tags: ["Examiner", "Oxford Alumni", "PhD Holder"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
  {
    id: 8102,
    name: "Aarav K.",
    subject: "Mathematics",
    grade: "IB MYP / DP",
    rating: 4.9,
    reviews: 96,
    experience: "6 Yrs",
    bio: "Known for clear concept breakdowns across algebra, functions, and probability. Aarav helps students bridge MYP foundations into advanced DP-level performance.",
    rate: "$68/hr",
    image: "",
    tags: ["Concept Clarity", "AA Specialist", "Fast Replies"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
  {
    id: 8103,
    name: "Maya R.",
    subject: "Mathematics",
    grade: "IB DP AI",
    rating: 4.9,
    reviews: 88,
    experience: "5 Yrs",
    bio: "Focused on AI pathways, internal assessment planning, and question pattern recognition. Maya keeps sessions structured and highly exam-relevant.",
    rate: "$64/hr",
    image: "",
    tags: ["IA Support", "AI Focused", "Interactive"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
];
