import type { CourseTutorProfile } from "./course-tutor-types";

export const ibSciencesTutorData: CourseTutorProfile[] = [
  {
    id: 8201,
    name: "James R.",
    subject: "Physics",
    grade: "IB DP Physics",
    rating: 4.9,
    reviews: 89,
    experience: "5 Yrs",
    bio: "Former lead physics teacher specializing in mechanics, electricity, and data analysis. Strong fit for IB students who need structure and confidence under timed conditions.",
    rate: "$65/hr",
    image: "/tutor_james_avatar_1775559651647.png",
    tags: ["Interactive", "Fast Replies", "Lead Teacher"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
  {
    id: 8202,
    name: "Nikita S.",
    subject: "Chemistry",
    grade: "IB DP Chemistry",
    rating: 4.9,
    reviews: 104,
    experience: "7 Yrs",
    bio: "Nikita simplifies organic chemistry, stoichiometry, and data-based questions with a very systematic approach tailored for IB marking criteria.",
    rate: "$72/hr",
    image: "",
    tags: ["HL Support", "Practical Skills", "Exam Focused"],
    accent: "bg-primary/10 text-primary border-primary/20",
    curriculum: "IB",
  },
  {
    id: 8203,
    name: "Rohan P.",
    subject: "Biology",
    grade: "IB DP Biology",
    rating: 4.8,
    reviews: 78,
    experience: "5 Yrs",
    bio: "Helps students master application-style biology questions, command terms, and structured extended responses across core and HL topics.",
    rate: "$63/hr",
    image: "",
    tags: ["Data Analysis", "HL Biology", "Patient"],
    accent: "bg-secondary/10 text-secondary border-secondary/20",
    curriculum: "IB",
  },
];
