/**
 * Regenerates src/lib/igcse-subjects/registry.ts from whatever subject modules
 * currently exist on disk. Static imports (not a dynamic glob) so the Next build
 * can trace and tree-shake the bundle, the same way generated-pages/registry.ts
 * is produced.
 *
 * Run after adding or removing a subject file:
 *   npx tsx scripts/igcse-subjects/build-registry.ts
 */
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const SUBJECTS_DIR = path.join(process.cwd(), "src", "lib", "igcse-subjects", "subjects");
const OUT = path.join(process.cwd(), "src", "lib", "igcse-subjects", "registry.ts");

function exportNameFor(slug: string): string {
  return slug.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

const slugs = readdirSync(SUBJECTS_DIR)
  .filter((file) => file.endsWith(".ts"))
  .map((file) => file.replace(/\.ts$/, ""))
  .sort();

const lines = [
  "/**",
  " * Generated by scripts/igcse-subjects/build-registry.ts — do not edit by hand.",
  " */",
  'import type { IgcseSubjectContent } from "./types";',
  ...slugs.map((slug) => `import { ${exportNameFor(slug)} } from "./subjects/${slug}";`),
  "",
  "export const igcseSubjectContents: IgcseSubjectContent[] = [",
  ...slugs.map((slug) => `  ${exportNameFor(slug)},`),
  "];",
  "",
];

writeFileSync(OUT, `${lines.join("\n")}\n`, { encoding: "utf8" });
console.log(`registry.ts written with ${slugs.length} subject${slugs.length === 1 ? "" : "s"}`);
