import type { RoleName } from "./roles";

export const PERMISSIONS = [
  "pages.read",
  "pages.create",
  "pages.update",
  "pages.delete",
  "pages.publish",
  "pages.archive",
  "seo.read",
  "seo.update",
  "internal_links.read",
  "internal_links.update",
  "tutors.read",
  "tutors.create",
  "tutors.update",
  "tutors.delete",
  "locations.read",
  "locations.create",
  "locations.update",
  "locations.delete",
  "assets.read",
  "assets.upload",
  "imports.read",
  "imports.create",
  "settings.read",
  "settings.update",
  "users.read",
  "users.create",
  "users.update",
  "users.delete",
  "audit.read",
] as const;

export type PermissionName = (typeof PERMISSIONS)[number];

const allPermissions = [...PERMISSIONS];
const readOnlyPermissions = PERMISSIONS.filter((permission) => permission.endsWith(".read"));

export const ROLE_PERMISSION_MAP: Record<RoleName, readonly PermissionName[]> = {
  super_admin: allPermissions,
  admin: allPermissions.filter((permission) => permission !== "users.delete"),
  seo_manager: [
    "pages.read",
    "seo.read",
    "seo.update",
    "internal_links.read",
    "internal_links.update",
    "locations.read",
    "assets.read",
    "settings.read",
    "audit.read",
  ],
  content_manager: [
    "pages.read",
    "pages.create",
    "pages.update",
    "pages.publish",
    "pages.archive",
    "seo.read",
    "internal_links.read",
    "internal_links.update",
    "assets.read",
    "assets.upload",
    "imports.read",
    "imports.create",
  ],
  tutor_manager: [
    "tutors.read",
    "tutors.create",
    "tutors.update",
    "tutors.delete",
    "locations.read",
    "assets.read",
    "assets.upload",
    "imports.read",
    "imports.create",
  ],
  editor: [
    "pages.read",
    "pages.create",
    "pages.update",
    "seo.read",
    "internal_links.read",
    "tutors.read",
    "locations.read",
    "assets.read",
  ],
  viewer: readOnlyPermissions,
};
