import type { GeneratedSeoPage } from "@/lib/page-generator/types";
import { gurgaonGeneratedSeoPages } from "@/lib/local-seo/gurgaon";

export const generatedSeoPages: GeneratedSeoPage[] = [
  ...gurgaonGeneratedSeoPages,
  {
    pageId: "IBG_GURUGRAM_SECTOR_56_IB_TUTORS",
    pageType: "sector",
    status: "review",
    indexFlag: "noindex",
    canonicalUrl: "https://www.ibgram.com/ib-tutors/gurugram/sectors/sector-56/",
    canonicalTarget: "https://www.ibgram.com/ib-tutors/gurugram/",
    slug: "sector-56",
    cityName: "Gurugram",
    citySlug: "gurugram",
    parentLocation: "Gurugram",
    microLocationName: "Sector 56",
    microLocationType: "sector",
    primaryKeyword: "IB tutors in Sector 56 Gurugram",
    secondaryKeywords: ["IB home tutors Sector 56", "IB DP tutor Sector 56", "IB Math AA tutor Gurugram"],
    serviceFocus: "IB tutors",
    programmes: ["PYP", "MYP", "DP"],
    subjects: ["Math AA", "Math AI", "Physics", "Chemistry", "Economics", "English"],
    tutoringModes: ["home", "online", "hybrid"],
    premiumAreas: ["Golf Course Road", "DLF Phase 5", "Sushant Lok", "Sector 57"],
    nearbyAreas: ["Golf Course Road", "Sushant Lok 2", "Sector 55", "Sector 57", "DLF Phase 5"],
    nearbyCities: ["Delhi", "Noida"],
    schoolsMentioned: ["Scottish High International School", "Lancers International School", "Pathways World School"],
    metaTitle: "IB Tutors in Sector 56 Gurugram | PYP, MYP & DP Support",
    metaDescription: "Find IB tutors in Sector 56 Gurugram for PYP, MYP and DP students. Home, online and hybrid support for Math AA, Physics and more.",
    ogTitle: "IB Tutors in Sector 56 Gurugram | IB Gram",
    ogDescription: "Sector 56 IB tutoring support with verified tutor matching for PYP, MYP, DP, Math AA, Physics, Chemistry and more.",
    ogImage: "https://www.ibgram.com/images/ib-gram-city-og.svg",
    twitterTitle: "IB Tutors in Sector 56 Gurugram | IB Gram",
    twitterDescription: "IB tutoring in Sector 56 Gurugram with home, online and hybrid options.",
    breadcrumbTitle: "IB Tutors in Sector 56",
    h1: "IB Tutors in Sector 56 Gurugram for PYP, MYP and DP Students",
    heroTitle: "Find Verified IB Tutors in Sector 56 Gurugram",
    heroSubtitle: "Local IB tutoring support for Sector 56 families who need programme-aware subject help, careful tutor matching and practical home, online or hybrid scheduling.",
    introSummary: "Sector 56 is close to several central Gurugram residential and school corridors, so families often need IB tutoring that is both academically specialist and realistic around travel windows.",
    contentBlocks: [
      {
        type: "intro",
        heading: "Local IB tutoring context in Sector 56",
        body: "Sector 56 families often sit between Golf Course Road, Sushant Lok, Sector 55, Sector 57 and DLF Phase 5. That makes tutor matching a practical decision as much as an academic one. A DP student may need a Math AA HL specialist who can support calculus, functions and timed exam practice. A younger MYP student may need help turning class discussions into criteria-ready assignments. IB Gram reviews the student's programme, current school pace, preferred mode and subject level before suggesting a tutor.",
        items: ["Sector 56 and nearby central Gurugram coverage", "Home tutoring reviewed by timing and travel feasibility", "Online backup for urgent doubts and specialist subjects"],
      },
      {
        type: "programmes",
        heading: "PYP, MYP and DP support",
        body: "PYP tutoring should keep learning curious and confidence-building. MYP tutoring usually needs criterion language, assignment structure and project planning. DP support is more specialist, with HL and SL subject depth, IA direction, exam revision and weekly academic accountability. Sector 56 requests commonly include a mix of programme planning and subject-specific intervention.",
        items: ["PYP reading, numeracy and inquiry support", "MYP criteria, evidence and reflection", "DP HL/SL subject tutoring, IA planning and exam practice"],
      },
      {
        type: "subjects",
        heading: "IB subjects commonly requested",
        body: "Math AA, Math AI, Physics, Chemistry, Economics and English are common starting points for IB families around Sector 56. Math AA HL and Math AI HL require different teaching habits, so IB Gram checks the exact pathway instead of treating every math request as the same. Science tutoring may include concept clarity, data questions and practical skills, while English and Economics often need writing structure and evidence.",
        items: ["Math AA HL, Math AA SL, Math AI HL and Math AI SL", "Physics and Chemistry HL/SL support", "Economics and English writing support"],
      },
      {
        type: "local_areas",
        heading: "Nearby areas and tutoring practicality",
        body: "Home tutoring may be feasible around Sector 56, Sector 55, Sector 57, Sushant Lok and Golf Course Road when tutor travel and lesson timing are realistic. For late evening lessons, rare subjects or exam-week urgency, online or hybrid support may give the student a stronger specialist match without adding commute pressure.",
        items: ["Sector 55 and Sector 57", "Golf Course Road and DLF Phase 5", "Sushant Lok and nearby residential pockets"],
      },
      {
        type: "schools",
        heading: "School ecosystem guidance",
        body: "Families in and around Sector 56 may be connected with international school ecosystems across Gurugram. IB Gram can help students plan support around school calendars, submission timelines, internal assessment milestones and exam sessions. The platform does not claim official partnership with schools unless specifically stated.",
        items: ["Calendar-aware tutoring", "IA and assessment planning with academic honesty boundaries", "Independent platform guidance"],
      },
      {
        type: "matching_process",
        heading: "Tutor matching process",
        body: "The matching process starts with the student's programme, grade, school timeline, subject level, current performance and preferred mode. IB Gram then checks whether the need is conceptual support, assignment support, exam preparation or a mix. A shortlist is built around subject fit, teaching style, availability, communication and location feasibility.",
        items: ["Share programme, subject, level and timing", "Review the academic need", "Shortlist by IB fit and availability", "Use a demo or diagnostic session where available"],
      },
      {
        type: "tutoring_modes",
        heading: "Home, online and hybrid options",
        body: "Sector 56 parents often ask for home lessons because younger students benefit from structure and accountability. Online lessons can be better for specialist DP topics, urgent revision and IA feedback. Hybrid plans can combine both: home sessions for routine support and online lessons for exam practice or subject-specific doubts.",
        items: ["Home tutoring where travel is practical", "Online tutoring for specialist reach", "Hybrid support for busy school weeks"],
      },
      {
        type: "verification",
        heading: "Tutor verification",
        body: "IB Gram reviews tutor profiles, subject depth, programme familiarity, communication style and feedback patterns before recommending a match. Parents should still use the first class to check clarity, pace and comfort. For DP work, tutors can guide thinking, structure and revision, but assessed work must remain student-owned.",
        items: ["Profile and subject review", "Teaching clarity and demo feedback", "Ongoing parent and student feedback"],
      },
      {
        type: "trust",
        heading: "Responsible local page note",
        body: "This seeded page is kept in review and noindex until the business team adds deeper verified Sector 56 information. The route, metadata, schema and renderer are production-ready, while publishing should happen only when local usefulness is strong enough.",
        items: ["No doorway-page publishing", "No fake building or school facts", "No overpromising outcomes"],
      },
      {
        type: "cta",
        heading: "Book a consultation",
        body: "Share the student's programme, subject level, school timeline, Sector 56 location details and preferred tutoring mode. IB Gram can review whether home, online or hybrid tutoring is the best next step.",
        items: ["Programme and subject review", "Mode recommendation", "Tutor shortlist where available"],
      },
    ],
    faqs: [
      { question: "How do I find IB tutors in Sector 56 Gurugram?", answer: "Share the student's programme, subject level, school timeline and preferred tutoring mode. IB Gram reviews the request and suggests suitable tutor options where available." },
      { question: "Is home tutoring available in Sector 56?", answer: "Home tutoring may be available depending on tutor location, timing and subject fit. Online or hybrid support can be suggested when it creates a stronger match." },
      { question: "Can Sector 56 students get Math AA HL support?", answer: "Yes, Math AA HL can be reviewed as a specialist DP request. IB Gram checks current topics, assessment deadlines and tutor availability before shortlisting." },
      { question: "Do tutors support IA and EE work?", answer: "Tutors can guide topic clarity, structure, research planning and revision. They should not write assessed work for the student." },
      { question: "Which nearby areas are covered?", answer: "Sector 55, Sector 57, Sushant Lok, Golf Course Road and DLF Phase 5 can be reviewed depending on tutor travel and schedule." },
      { question: "Is IB Gram affiliated with schools near Sector 56?", answer: "IB Gram is an independent tutoring platform and is not officially affiliated with this school unless specifically stated." },
    ],
    internalLinks: [],
    relatedPageSuggestions: [],
    schema: {},
    quality: {
      wordCount: 1250,
      uniquenessScore: 76,
      localDepthScore: 82,
      seoScore: 69,
      readabilityScore: 90,
      internalLinkScore: 0,
      duplicateRisk: "medium",
      recommendedIndexFlag: "noindex",
      warnings: ["Seed page is intentionally review/noindex until expanded to 1600+ words with verified local depth."],
    },
    finalCta: "Book a free academic consultation for Sector 56 IB tutoring support.",
    lastUpdated: "2026-05-05",
  },
];
