/**
 * Compiles agent-written page JSON (tmp/seo/out/*.json) into sharded bundles under
 * src/lib/generated-pages/pages/ plus a static-import registry.
 * Run: npx tsx scripts/seo-content/compile-pages.ts
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { validateGeneratedSeoPage } from "../../src/lib/page-generator/validators";
import type { GeneratedSeoPage } from "../../src/lib/page-generator/types";

const ROOT = process.cwd();
const IN_DIR = path.join(ROOT, "tmp", "seo", "out");
const PAGES_DIR = path.join(ROOT, "src", "lib", "generated-pages", "pages");
const REGISTRY = path.join(ROOT, "src", "lib", "generated-pages", "registry.ts");

function shardFor(page: GeneratedSeoPage): string {
  const route = page.canonicalUrl.replace(/^https?:\/\/[^/]+/i, "");
  const curriculum = route.startsWith("/igcse") ? "igcse" : "ib";
  return `${curriculum}-${page.pageType}`;
}

const files = existsSync(IN_DIR) ? readdirSync(IN_DIR).filter((f) => f.endsWith(".json")).sort() : [];
const byRoute = new Map<string, GeneratedSeoPage>();
const errors: string[] = [];

for (const file of files) {
  try {
    const raw = JSON.parse(readFileSync(path.join(IN_DIR, file), "utf8"));
    const page = validateGeneratedSeoPage(raw.page ?? raw);
    const route = page.canonicalUrl.replace(/^https?:\/\/[^/]+/i, "");
    if (byRoute.has(route)) errors.push(`duplicate route ${route} (${file})`);
    byRoute.set(route, page);
  } catch (error) {
    errors.push(`${file}: ${(error as Error).message}`);
  }
}

const shards = new Map<string, GeneratedSeoPage[]>();
for (const page of byRoute.values()) {
  const key = shardFor(page);
  if (!shards.has(key)) shards.set(key, []);
  shards.get(key)!.push(page);
}

rmSync(PAGES_DIR, { recursive: true, force: true });
mkdirSync(PAGES_DIR, { recursive: true });

const shardNames = [...shards.keys()].sort();
for (const name of shardNames) {
  const pages = shards.get(name)!.sort((a, b) => a.canonicalUrl.localeCompare(b.canonicalUrl));
  writeFileSync(path.join(PAGES_DIR, `${name}.json`), `${JSON.stringify(pages, null, 1)}\n`, "utf8");
}

const imports = shardNames.map((name, i) => `import shard${i} from "./pages/${name}.json";`).join("\n");
const spread = shardNames.map((_, i) => `  ...(shard${i} as unknown as GeneratedSeoPage[]),`).join("\n");

writeFileSync(
  REGISTRY,
  `/**\n * Generated by scripts/seo-content/compile-pages.ts — do not edit by hand.\n * Static imports keep the bundles traceable for the Next build.\n */\nimport type { GeneratedSeoPage } from "@/lib/page-generator/types";\n${imports ? `${imports}\n` : ""}\nexport const seoContentPages: GeneratedSeoPage[] = [\n${spread}\n];\n`,
  "utf8",
);

console.log(`Compiled ${byRoute.size} pages into ${shardNames.length} shards.`);
shardNames.forEach((n) => console.log(`  ${n}: ${shards.get(n)!.length}`));

// The store merges compiled pages with generated-pages.local.json and dedupes by
// pageId, but the route lookup is keyed by path and the local file is merged last.
// So a local entry sharing a compiled page's path under a different pageId silently
// shadows it at render time. Surface that here instead of losing it in the browser.
const LOCAL_STORE = path.join(process.cwd(), "src", "lib", "generated-pages", "generated-pages.local.json");
if (existsSync(LOCAL_STORE)) {
  const shadowed = (JSON.parse(readFileSync(LOCAL_STORE, "utf8")) as GeneratedSeoPage[])
    .map((p) => ({ path: new URL(p.canonicalUrl).pathname, pageId: p.pageId }))
    .filter((p) => byRoute.has(p.path) && byRoute.get(p.path)!.pageId !== p.pageId);
  if (shadowed.length) {
    console.error(`\n${shadowed.length} compiled page(s) shadowed by generated-pages.local.json:`);
    shadowed.forEach((p) => console.error(`  - ${p.path} (local pageId ${p.pageId} wins at render time)`));
    process.exitCode = 1;
  }
}
if (errors.length) {
  console.error(`\n${errors.length} problem(s):`);
  errors.slice(0, 40).forEach((e) => console.error(`  - ${e}`));
  process.exitCode = 1;
}
