// AUTO-GENERATED by scripts/gurgaon-500/compile.ts — do not edit by hand.
// Content for the Gurugram subject x area expansion. Shipped as two JSON shards rather
// than one module per slug: identical rendered output, one import instead of hundreds.
import type { GurgaonSeoContent } from "../../types";
import ibShard from "./ib.json";
import igcseShard from "./igcse.json";

const all = [...(ibShard as GurgaonSeoContent[]), ...(igcseShard as GurgaonSeoContent[])];

export const gurgaonSeoExpansionContentBySlug: Record<string, GurgaonSeoContent> = Object.fromEntries(
  all.map((c) => [c.slug, c]),
);
