/**
 * The 48 country landing pages that follow /usa/. One module per row at
 * src/lib/country-seo/countries/<slug>.ts exporting `const <exportName>: CountrySeoPage`.
 * `angle` is a starting brief of country-specific facts to build unique content on —
 * writers must verify anything they are not certain of, and may go well beyond it.
 */
export interface CountryPlan {
  slug: string;
  exportName: string;
  name: string;
  flagCode: string;
  countryCode: string;
  angle: string;
}

export const COUNTRY_PLAN: CountryPlan[] = [
  // The original page, listed so the gate checks it too; the registry always imports it first.
  { slug: "usa", exportName: "usa", name: "United States", flagCode: "us", countryCode: "US", angle: "Roughly 1,900 IB World Schools, mostly public districts; IB vs AP; Cambridge AICE in Florida; May session; six time zones; HL credit policies set institution by institution." },
  { slug: "uk", exportName: "uk", name: "United Kingdom", flagCode: "gb", countryCode: "GB", angle: "GCSE/A Level vs IB; UCAS and Oxbridge offers in IB points and HL 7s; independent schools running Cambridge/Edexcel IGCSE; state sixth forms offering IB; London, Surrey, Oxford, Edinburgh; GMT/BST; Year 10-13 naming; May session." },
  { slug: "uae", exportName: "uae", name: "United Arab Emirates", flagCode: "ae", countryCode: "AE", angle: "KHDA (Dubai), ADEK (Abu Dhabi), SPEA (Sharjah) inspections; MoE equivalency for IB/IGCSE; mandatory Arabic, Islamic Studies and Moral/Social Studies; Dubai, Abu Dhabi, Sharjah; GST UTC+4 no DST; Mon-Fri week with short Friday; Ramadan timetables; British vs IB schools." },
  { slug: "singapore", exportName: "singapore", name: "Singapore", flagCode: "sg", countryCode: "SG", angle: "MOE, Integrated Programme, local schools offering IB DP; Singapore as a high-scoring IB centre; international schools (UWCSEA, Tanglin, Dulwich); NUS/NTU/SMU admission with IB; SGT UTC+8; November session at some schools." },
  { slug: "china", exportName: "china", name: "China", flagCode: "cn", countryCode: "CN", angle: "Foreign-passport international schools vs Chinese-owned bilingual schools; Beijing, Shanghai, Shenzhen, Guangzhou; gaokao contrast; Chinese A/B; CST UTC+8; video-platform connectivity considerations; A Level popularity; overseas university pipeline." },
  { slug: "australia", exportName: "australia", name: "Australia", flagCode: "au", countryCode: "AU", angle: "HSC, VCE, QCE, WACE vs IB; UAC/VTAC/QTAC conversion of IB scores; many schools sit the November session; AEST/ACST/AWST and which states use daylight saving; Sydney, Melbourne, Brisbane, Perth, Canberra; independent grammar schools." },
  { slug: "canada", exportName: "canada", name: "Canada", flagCode: "ca", countryCode: "CA", angle: "Provincial diplomas (OSSD, BC Dogwood, Alberta) alongside IB in public boards; Quebec CEGEP route; French immersion and French B; UofT, UBC, McGill IB admission; six time zones; Toronto, Vancouver, Calgary, Montreal, Ottawa." },
  { slug: "spain", exportName: "spain", name: "Spain", flagCode: "es", countryCode: "ES", angle: "Bachillerato and PAU/EBAU; UNEDasiss accreditation and homologación for IB/A Level students entering Spanish universities; Madrid, Barcelona, Valencia, Costa del Sol; Canary Islands on WET; British schools with IGCSE; Spanish A." },
  { slug: "switzerland", exportName: "switzerland", name: "Switzerland", flagCode: "ch", countryCode: "CH", angle: "The IB's Geneva origins; cantonal Matura; swissuniversities subject-combination requirements for IB holders; Geneva, Zurich, Lausanne, Basel, Zug; boarding schools; French/German A and B; CET." },
  { slug: "hong-kong", exportName: "hongKong", name: "Hong Kong", flagCode: "hk", countryCode: "HK", angle: "HKDSE vs IB; ESF schools across the IB continuum; DSS schools offering IB; JUPAS vs non-JUPAS admissions; Chinese A/B and Mandarin vs Cantonese; HKT UTC+8; Hong Kong Island, Kowloon, New Territories." },
  { slug: "malaysia", exportName: "malaysia", name: "Malaysia", flagCode: "my", countryCode: "MY", angle: "SPM/STPM vs IGCSE, A Level and IB; very large IGCSE market; Kuala Lumpur, Mont Kiara, Penang, Johor EduCity; Bahasa Malaysia requirements for citizens; MYT UTC+8; pre-university foundation routes." },
  { slug: "thailand", exportName: "thailand", name: "Thailand", flagCode: "th", countryCode: "TH", angle: "Bangkok, Chiang Mai, Phuket, Pattaya; British-curriculum schools with IGCSE then IB or A Level; Thai language requirement for Thai nationals; TCAS and Thai international programmes; ICT UTC+7." },
  { slug: "indonesia", exportName: "indonesia", name: "Indonesia", flagCode: "id", countryCode: "ID", angle: "SPK (Satuan Pendidikan Kerjasama) schools and compulsory Bahasa Indonesia, religion and Pancasila for citizens; Jakarta, Bali, Surabaya, Bandung; three time zones WIB/WITA/WIT; overseas university pipeline." },
  { slug: "saudi-arabia", exportName: "saudiArabia", name: "Saudi Arabia", flagCode: "sa", countryCode: "SA", angle: "Vision 2030 education reform; international schools admitting Saudi nationals; Riyadh, Jeddah, Dammam/Al Khobar; MoE equivalency; Qudurat/Tahsili context; AST UTC+3; Sun-Thu week; Ramadan scheduling." },
  { slug: "qatar", exportName: "qatar", name: "Qatar", flagCode: "qa", countryCode: "QA", angle: "Education City and Qatar Foundation; branch campuses (Texas A&M, Georgetown, Carnegie Mellon, Weill Cornell) admitting IB and A Level students; MoEHE private-school licensing; Doha, Al Wakrah, Al Khor; AST UTC+3." },
  { slug: "south-africa", exportName: "southAfrica", name: "South Africa", flagCode: "za", countryCode: "ZA", angle: "NSC and IEB matric vs Cambridge and IB; USAf Matriculation Board exemption for foreign qualifications; November session common; Johannesburg, Pretoria, Cape Town, Durban; SAST UTC+2; load-shedding and backup connectivity." },
  { slug: "new-zealand", exportName: "newZealand", name: "New Zealand", flagCode: "nz", countryCode: "NZ", angle: "NCEA vs Cambridge (widely offered in NZ schools) and IB; University Entrance via CIE or IB; November sessions; Auckland, Wellington, Christchurch; NZST/NZDT; independent schools." },
  { slug: "japan", exportName: "japan", name: "Japan", flagCode: "jp", countryCode: "JP", angle: "MEXT drive to expand IB; Dual Language Diploma Programme taught partly in Japanese; IB entry routes at Japanese universities; April school year vs August international schools; Tokyo, Yokohama, Osaka, Kobe; JST UTC+9." },
  { slug: "south-korea", exportName: "southKorea", name: "South Korea", flagCode: "kr", countryCode: "KR", angle: "Suneung (CSAT) and hagwon culture; Jeju Global Education City; public schools adopting Korean-language IB (Daegu, Jeju); foreign schools in Seoul; KST UTC+9; US and UK university pipeline." },
  { slug: "turkey", exportName: "turkey", name: "Türkiye", flagCode: "tr", countryCode: "TR", angle: "MEB national curriculum alongside IB DP in private schools; YKS and university entry for citizens; denklik (equivalence) of foreign diplomas; Istanbul, Ankara, Izmir; Turkish A; TRT UTC+3. Use both Türkiye and Turkey." },
  { slug: "netherlands", exportName: "netherlands", name: "Netherlands", flagCode: "nl", countryCode: "NL", angle: "VWO/HAVO; Dutch International Schools (DIS) subsidised network; The Hague's international organisations; Amsterdam, Rotterdam, Eindhoven; English-taught bachelors and numerus fixus; CET." },
  { slug: "germany", exportName: "germany", name: "Germany", flagCode: "de", countryCode: "DE", angle: "Abitur; KMK subject requirements for recognising the IB Diploma as university entrance; Berlin, Munich, Frankfurt, Hamburg, Düsseldorf, Stuttgart; German A/B; CET." },
  { slug: "france", exportName: "france", name: "France", flagCode: "fr", countryCode: "FR", angle: "Reformed baccalauréat; BFI (replaced OIB); Parcoursup for IB students; Paris region, Lyon, Sophia Antipolis/Nice; French A/B; CET." },
  { slug: "mexico", exportName: "mexico", name: "Mexico", flagCode: "mx", countryCode: "MX", angle: "SEP revalidation; Spanish-language IB DP; Mexico City, Monterrey, Guadalajara, Puebla; bilingual private schools; Mexico largely without daylight saving since 2022; UNAM/Tec/UDLAP admission; US university pipeline." },
  { slug: "brazil", exportName: "brazil", name: "Brazil", flagCode: "br", countryCode: "BR", angle: "ENEM and vestibular vs IB; bilingual school growth; São Paulo, Rio de Janeiro, Brasília, Curitiba; school year February-December vs international calendars; revalidation of foreign diplomas; Portuguese A; BRT UTC-3." },
  { slug: "vietnam", exportName: "vietnam", name: "Vietnam", flagCode: "vn", countryCode: "VN", angle: "National high school graduation exam; MOET rules on international schools and Vietnamese enrolment; Hanoi, Ho Chi Minh City, Da Nang; British schools with IGCSE then IB; ICT UTC+7." },
  { slug: "pakistan", exportName: "pakistan", name: "Pakistan", flagCode: "pk", countryCode: "PK", angle: "Cambridge O Level/A Level dominance and where IGCSE and IB fit; IBCC equivalence to Matric/FSc; MDCAT and local university entry; Karachi, Lahore, Islamabad; PKT UTC+5; power and connectivity backups. Stay strictly non-political." },
  { slug: "kenya", exportName: "kenya", name: "Kenya", flagCode: "ke", countryCode: "KE", angle: "CBC replacing 8-4-4 and KCSE; KNQA equivalence; KUCCPS placement; British-curriculum IGCSE/A Level schools and IB schools; Nairobi (Westlands, Karen, Runda), Mombasa; EAT UTC+3." },
  { slug: "egypt", exportName: "egypt", name: "Egypt", flagCode: "eg", countryCode: "EG", angle: "Thanaweya Amma; Supreme Council of Universities equivalency rules for IGCSE/American/IB students; Cairo (New Cairo, Sheikh Zayed, 6th of October), Alexandria; Egypt reinstated summer time in 2023." },
  { slug: "nigeria", exportName: "nigeria", name: "Nigeria", flagCode: "ng", countryCode: "NG", angle: "WAEC WASSCE, NECO and JAMB UTME vs Cambridge IGCSE/A Level and IB; Lagos (Ikoyi, Lekki, VI), Abuja, Port Harcourt; WAT UTC+1; power and data reliability; UK/US/Canada university pipeline." },
  { slug: "bangladesh", exportName: "bangladesh", name: "Bangladesh", flagCode: "bd", countryCode: "BD", angle: "English-medium schools with Cambridge/Edexcel O and A Levels; SSC/HSC; Education Board equivalence for local university admission; Dhaka (Gulshan, Baridhara, Dhanmondi), Chattogram; BST UTC+6." },
  { slug: "oman", exportName: "oman", name: "Oman", flagCode: "om", countryCode: "OM", angle: "Ministry of Education private-school oversight; Muscat, Sohar, Salalah; Sultan Qaboos University entry; British and American curricula alongside IB; GST UTC+4; Sun-Thu week." },
  { slug: "kuwait", exportName: "kuwait", name: "Kuwait", flagCode: "kw", countryCode: "KW", angle: "Private Education department equivalency; strong American-curriculum sector alongside British and bilingual IB schools; Kuwait City, Salmiya, Hawalli, Ahmadi; Kuwait University entry; AST UTC+3." },
  { slug: "bahrain", exportName: "bahrain", name: "Bahrain", flagCode: "bh", countryCode: "BH", angle: "BQA (Education & Training Quality Authority) reviews; Manama, Riffa, Saar, Juffair; University of Bahrain entry; families crossing the causeway from Saudi Arabia; AST UTC+3." },
  { slug: "philippines", exportName: "philippines", name: "Philippines", flagCode: "ph", countryCode: "PH", angle: "DepEd K-12 senior high; CHED; UPCAT/ACET college tests; Metro Manila (BGC Taguig, Makati, Alabang), Cebu; PHT UTC+8; typhoon-season and connectivity planning." },
  { slug: "portugal", exportName: "portugal", name: "Portugal", flagCode: "pt", countryCode: "PT", angle: "DGES equivalence and national exams as entry prerequisites for Portuguese universities; relocating and remote-working families; Lisbon/Cascais, Porto, Algarve; Portuguese A; WET/WEST, Azores UTC-1." },
  { slug: "italy", exportName: "italy", name: "Italy", flagCode: "it", countryCode: "IT", angle: "Esame di Stato (maturità); dichiarazione di valore for university enrolment; IMAT and English-taught degrees; Rome, Milan, Florence, Turin; Italian A; CET." },
  { slug: "sweden", exportName: "sweden", name: "Sweden", flagCode: "se", countryCode: "SE", angle: "Gymnasium and högskoleprovet; tuition-free IB DP in some municipal schools; UHR conversion of IB grades; Swedish language entry requirements; Stockholm, Gothenburg, Malmö; CET." },
  { slug: "belgium", exportName: "belgium", name: "Belgium", flagCode: "be", countryCode: "BE", angle: "EU institutions and NATO/SHAPE families; European Baccalaureate as the alternative; equivalence via the French and Flemish communities; Brussels, Antwerp, Waterloo, Mons; French/Dutch B; CET." },
  { slug: "ireland", exportName: "ireland", name: "Ireland", flagCode: "ie", countryCode: "IE", angle: "Leaving Certificate and CAO points; the CAO scale for IB grades; Irish language exemption for students educated abroad; Dublin, Cork, Galway; GMT/IST." },
  { slug: "austria", exportName: "austria", name: "Austria", flagCode: "at", countryCode: "AT", angle: "Matura; Vienna's UN/OPEC/IAEA community; recognition of the IB Diploma for Austrian university entry; Vienna, Salzburg, Graz, Linz, Innsbruck; German A/B; CET." },
  { slug: "denmark", exportName: "denmark", name: "Denmark", flagCode: "dk", countryCode: "DK", angle: "STX/HHX/HTX gymnasium; state gymnasiums offering IB DP; kvote 1/kvote 2 admission and conversion of IB results to Danish grades; Copenhagen, Aarhus, Odense, Billund; CET." },
  { slug: "norway", exportName: "norway", name: "Norway", flagCode: "no", countryCode: "NO", angle: "Videregående school; IB DP in public schools; Samordna opptak and the Norwegian language requirement; Oslo, Bergen, Stavanger, Trondheim; CET." },
  { slug: "finland", exportName: "finland", name: "Finland", flagCode: "fi", countryCode: "FI", angle: "Ylioppilastutkinto (matriculation exam); tuition-free IB in public upper secondary schools; certificate-based admission quotas for IB holders; Helsinki, Espoo, Tampere, Turku; EET UTC+2/+3." },
  { slug: "poland", exportName: "poland", name: "Poland", flagCode: "pl", countryCode: "PL", angle: "Matura; IB Diploma recognised for Polish university entry; public liceum IB classes; Warsaw, Kraków, Wrocław, Gdańsk, Poznań; Polish A; CET." },
  { slug: "sri-lanka", exportName: "sriLanka", name: "Sri Lanka", flagCode: "lk", countryCode: "LK", angle: "GCE O/L and A/L national exams vs Cambridge/Edexcel London exams in international schools; UGC admission; Colombo, Kandy, Galle; SLST UTC+5:30, the same clock as our tutors." },
  { slug: "nepal", exportName: "nepal", name: "Nepal", flagCode: "np", countryCode: "NP", angle: "SEE and NEB Grade 11-12; Cambridge A Level colleges in Kathmandu; NEB equivalence; study-abroad pipeline (Australia, US, UK, Japan); Kathmandu, Lalitpur, Pokhara; NPT UTC+5:45, 15 minutes ahead of India." },
  { slug: "jordan", exportName: "jordan", name: "Jordan", flagCode: "jo", countryCode: "JO", angle: "Tawjihi; Ministry of Education equivalence for IB/IGCSE; Amman and Madaba; Jordan on permanent UTC+3 since 2022; Arabic A." },
  { slug: "czech-republic", exportName: "czechRepublic", name: "Czech Republic", flagCode: "cz", countryCode: "CZ", angle: "Maturita; nostrifikace (recognition) of foreign diplomas; Prague and Brno; British and IB international schools; Czech A; CET. Use both Czech Republic and Czechia." },
  { slug: "india", exportName: "india", name: "India", flagCode: "in", countryCode: "IN", angle: "Roughly 230 IB World Schools and a very large Cambridge/Edexcel IGCSE network; CBSE, CISCE (ICSE/ISC) and state boards; AIU equivalence for IB DP and IGCSE; CUET-UG, JEE and NEET eligibility; NEP 2020; Delhi NCR, Mumbai, Bengaluru, Hyderabad, Chennai, Pune, Kolkata, Ahmedabad; IST UTC+5:30, the same clock as our tutors; home tuition available in Gurugram and parts of Delhi NCR, online everywhere else." },
];
