export interface IGCSESubjectGroup {
  title: string;
  entries: string[];
}

export const igcseSubjectGroups: IGCSESubjectGroup[] = [
  { title: "Accounting", entries: ["Accounting - 0452", "Accounting - 0985"] },
  { title: "Afrikaans", entries: ["Afrikaans - 0512", "Afrikaans - 0548"] },
  { title: "Agriculture", entries: ["Agriculture - 0600"] },
  { title: "Arabic", entries: ["Arabic - 0508", "Arabic - 0527", "Arabic - 0544", "Arabic - 7180 - UK", "Arabic - 7184"] },
  { title: "Art and Design", entries: ["Art and Design - 0400", "Art and Design - 0415", "Art and Design - 0989"] },
  { title: "Bahasa Indonesia", entries: ["Bahasa Indonesia - 0538"] },
  { title: "Bangladesh Studies", entries: ["Bangladesh Studies - 0449"] },
  { title: "Biology", entries: ["Biology - 0438", "Biology - 0610", "Biology - 0970"] },
  { title: "Business Studies", entries: ["Business Studies - 0450", "Business Studies - 0986 - UK"] },
  { title: "Chemistry", entries: ["Chemistry - 0439", "Chemistry - 0620", "Chemistry - 0971 - UK"] },
  { title: "Child Development", entries: ["Child Development - 0637"] },
  { title: "Chinese", entries: ["Chinese - 0509", "Chinese - 0523", "Chinese - 0534", "Chinese - 0547"] },
  { title: "Computer Science", entries: ["Computer Science - 0478", "Computer Science - 0984"] },
  { title: "Computer Studies", entries: ["Computer Studies - 0420", "Computer Studies - 0441"] },
  { title: "Czech - First Language", entries: ["Czech - First Language - 0514"] },
  { title: "Design and Technology", entries: ["Design and Technology - 0445", "Design and Technology - 0979"] },
  { title: "Development Studies", entries: ["Development Studies - 0453"] },
  { title: "Drama", entries: ["Drama - 0411", "Drama - 0428", "Drama - 0994"] },
  { title: "Dutch", entries: ["Dutch - 0503", "Dutch - 0515"] },
  { title: "Economics", entries: ["Economics - 0437", "Economics - 0455", "Economics - 0987"] },
  { title: "English", entries: ["English - 0427", "English - 0476", "English - 0477", "English - 0486", "English - 0500", "English - 0510", "English - 0511", "English - 0522", "English - 0524", "English - 0526", "English - 0627", "English - 0772", "English - 0990", "English - 0991", "English - 0993", "English - 0475", "English - 0472", "English - 0992"] },
  { title: "English (as a Second Language)", entries: ["English (as a Second Language) - 0485"] },
  { title: "Enterprise", entries: ["Enterprise - 0454"] },
  { title: "Environmental Management", entries: ["Environmental Management - 0680"] },
  { title: "Food and Nutrition", entries: ["Food and Nutrition - 0648"] },
  { title: "French", entries: ["French - 0501", "French - 0520", "French - 0528", "French - 0685 (UK)", "French - 7156"] },
  { title: "Geography", entries: ["Geography - 0460", "Geography - 0976"] },
  { title: "German", entries: ["German - 0505", "German - 0525", "German - 0529", "German - 0677", "German - 7159 - UK"] },
  { title: "Global Perspectives", entries: ["Global Perspectives - 0426", "Global Perspectives - 0457"] },
  { title: "Greek", entries: ["Greek - 0536", "Greek - 0543"] },
  { title: "Hindi", entries: ["Hindi - 0549"] },
  { title: "History", entries: ["History - 0416", "History - 0470", "History - 0977", "History - American - 0409"] },
  { title: "ICT", entries: ["ICT - 0417", "Information and Communication Technology (9-1) - 0983"] },
  { title: "India Studies", entries: ["India Studies - 0447"] },
  { title: "Indonesian", entries: ["Indonesian - 0545"] },
  { title: "IsiZulu", entries: ["IsiZulu - 0531"] },
  { title: "Islamiyat", entries: ["Islamiyat - 0493"] },
  { title: "Italian", entries: ["Italian - 0535", "Italian - 7164"] },
  { title: "Japanese", entries: ["Japanese - 0507", "Japanese - 0519"] },
  { title: "Kazakh", entries: ["Kazakh - 0532"] },
  { title: "Korean", entries: ["Korean - 0521"] },
  { title: "Latin", entries: ["Latin - 0480"] },
  { title: "Malay", entries: ["Malay - 0546", "Malay - First Language - 0696"] },
  { title: "Marine Science", entries: ["Marine Science (Maldives only) - 0697"] },
  { title: "Mathematics", entries: ["Mathematics - 0444", "Mathematics - 0459", "Mathematics - 0580", "Mathematics - 0581", "Mathematics - 0606", "Mathematics - 0607", "Mathematics - 0626", "Mathematics - 0980"] },
  { title: "Music", entries: ["Music - 0410", "Music - 0429", "Music - 0978 - UK"] },
  { title: "Pakistan Studies", entries: ["Pakistan Studies - 0448"] },
  { title: "Physical Education", entries: ["Physical Education - 0413", "Physical Education - 0995"] },
  { title: "Physical Science", entries: ["Physical Science - 0652"] },
  { title: "Physics", entries: ["Physics - 0443", "Physics - 0625", "Physics - 0972"] },
  { title: "Portuguese", entries: ["Portuguese - 0504", "Portuguese - 0540"] },
  { title: "Religious Studies", entries: ["Religious Studies - 0490"] },
  { title: "Russian", entries: ["Russian - 0516"] },
  { title: "Sanskrit", entries: ["Sanskrit - 0499"] },
  { title: "Science", entries: ["Science - 0653"] },
  { title: "Sciences", entries: ["Sciences - 0442", "Sciences - 0654", "Sciences - 0973"] },
  { title: "Setswana", entries: ["Setswana - First Language - 0698"] },
  { title: "Sociology", entries: ["Sociology - 0495"] },
  { title: "Spanish", entries: ["Spanish - 0474", "Spanish - 0502", "Spanish - 0530", "Spanish - 0533", "Spanish - 0537", "Spanish - 0678", "Spanish - 7160"] },
  { title: "Spanish Literature", entries: ["Spanish Literature - 0488"] },
  { title: "Swahili", entries: ["Swahili - 0262"] },
  { title: "Thai", entries: ["Thai - 0518"] },
  { title: "Travel and Tourism", entries: ["Travel and Tourism - 0471"] },
  { title: "Turkish", entries: ["Turkish - 0513"] },
  { title: "Twenty-First Century Science", entries: ["Twenty-First Century Science - 0608"] },
  { title: "Urdu", entries: ["Urdu - 0539"] },
  { title: "Vietnamese", entries: ["Vietnamese - First Language - 0695"] },
  { title: "World Literature", entries: ["World Literature - 0408"] },
];
