// One entry per blog post to rewrite (every post except the reference AA HL guide).
// `key` is the post's slug; `old` is set only where the stored slug was a title and gets renamed.
// `lane` is what this post owns; siblings in the same cluster own the rest.
//
//   npx tsx scripts/blog-rewrite/plan.ts <key>   # print the writer brief for one post
import { readFileSync } from "node:fs";

type Cat = "local-guides" | "parent-resources" | "exam-strategy" | "dp-planning" | "subject-choice" | "igcse-revision";
export type Entry = {
  key: string;
  old?: string;
  kw: string;
  lane: string;
  cluster: string;
  cat: Cat;
  ajay?: boolean; // maths post bylined to Ajay Vatsyayan
  pillar?: boolean; // links to every sibling in its cluster
};

const L = "local-ib", G = "local-igcse", D = "ib-decisions", M = "ib-maths", Y = "myp-maths", S = "ib-sciences", C = "ib-core-exams", I = "igcse-guides";

export const REFERENCE = "how-to-score-7-ib-math-aa-hl";

export const PLAN: Entry[] = [
  { key: "ib-dp-core-planning-timeline", kw: "IB DP core timeline", lane: "Two-year calendar for CAS, the Extended Essay and Theory of Knowledge together: what is due when, how the three collide with subject IAs, and a term-by-term plan that avoids the DP2 crunch.", cluster: C, cat: "dp-planning" },
  { key: "igcse-revision-six-week-plan", kw: "six-week IGCSE revision plan", lane: "A week-by-week six-week multi-subject IGCSE revision plan before the exam series: triage, spaced retrieval, past-paper weeks, the final week. Multi-subject, not maths only.", cluster: I, cat: "igcse-revision" },
  { key: "stem-subject-choice-ib-dp", kw: "IB DP STEM subject choice", lane: "Choosing HL/SL maths and science combinations for engineering, medicine, computer science and pure science; checking university requirements; the regret scenarios and how to avoid them.", cluster: S, cat: "subject-choice" },
  { key: "best-ib-igcse-tutors-gurgaon-delhi-ncr", kw: "IB and IGCSE tutors in Gurgaon", lane: "Hub guide for Gurgaon and Delhi NCR families on both boards: how IB and IGCSE tutoring needs differ, an area-by-area overview table, and a link to every area guide in the cluster.", cluster: L, cat: "local-guides", pillar: true },
  { key: "ib-igcse-tutors-south-delhi", kw: "IB and IGCSE tutors in South Delhi", lane: "South Delhi localities (Greater Kailash, Defence Colony, Saket, Hauz Khas, Vasant Vihar, Panchsheel): when home tuition is practical in South Delhi evenings, when online wins, both boards.", cluster: L, cat: "local-guides" },
  { key: "top-ib-igcse-tutors-noida", kw: "IB and IGCSE tutors in Noida", lane: "Noida sectors (Sector 44, 50, 62, 128, 137, Noida Expressway): international-school calendars, matching a home tutor in Noida, both boards.", cluster: L, cat: "local-guides" },
  { key: "ib-igcse-tutors-greater-noida", kw: "IB and IGCSE tutors in Greater Noida", lane: "Greater Noida and Greater Noida West: thinner specialist supply, why online and hybrid matter more here, how to make a hybrid plan work. Honest about limits.", cluster: L, cat: "local-guides" },
  { key: "best-ib-tutors-faridabad", kw: "IB tutors in Faridabad", lane: "IB only, Faridabad (Sector 15, 21, NIT, Greater Faridabad): DP subject support, which subjects work online from Faridabad, how to judge a tutor here.", cluster: L, cat: "local-guides" },
  { key: "ib-exam-preparation-dwarka", kw: "IB exam preparation in Dwarka", lane: "Exam-prep lens for Dwarka families: the countdown to the May session, mock recovery, paper practice cadence, home vs online in Dwarka sectors.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-vasant-kunj", kw: "IB tutors in Vasant Kunj", lane: "Vasant Kunj sectors and pockets, Mahipalpur and the Gurgaon border: DP subject support, families straddling Delhi and Gurgaon schools.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-golf-course-road-gurgaon", kw: "IB tutors near Golf Course Road", lane: "High-rise societies along Golf Course Road (Sectors 42, 43, 53, 54): gate entry, evening slots, DP HL subject depth, home study setup.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-dlf-phase-5-gurgaon", kw: "IB tutors in DLF Phase 5", lane: "DLF Phase 5 families: the MYP 5 to DP1 transition year, choosing HL subjects, a tutor who can carry a student across both programmes.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-sector-56-gurgaon", kw: "IB tutors in Sector 56 Gurgaon", lane: "Sector 56 and nearby Golf Course Extension Road: MYP students, weekday after-school scheduling, building a weekly rhythm around school and activities.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-sector-57-gurgaon", kw: "IB tutors in Sector 57 Gurgaon", lane: "Sector 57 and Sushant Lok adjacency: coursework season support (IA drafts, EE milestones) within academic integrity rules, for DP students here.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-cyber-city-gurgaon", kw: "IB tutors near Cyber City Gurgaon", lane: "Working-parent households around Cyber City and DLF Phase 2/3: late-evening and online slots, parent update cadence, what to ask for when you cannot sit in.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-sushant-lok-gurgaon", kw: "IB tutors in Sushant Lok", lane: "Sushant Lok 1, 2 and 3: independent floors vs societies, study space at home, planning tutors for siblings or several DP subjects in one household.", cluster: L, cat: "local-guides" },
  { key: "ib-tutors-delhi-ncr", kw: "IB tutors in Delhi NCR", lane: "IB only, NCR-wide: a decision guide on home vs online by where you live across Delhi, Gurgaon, Noida, Faridabad and Ghaziabad; DP and MYP subject coverage.", cluster: L, cat: "local-guides" },
  { key: "online-ib-tutoring-india", kw: "online IB tutoring in India", lane: "How online IB tutoring works well: pen tablets, shared whiteboards, GDC on screen, session structure, families in any Indian city or abroad; when online is the wrong choice.", cluster: D, cat: "parent-resources" },
  { key: "personalized-home-tuition-ib-students", kw: "personalised home tuition for IB students", lane: "What personalisation means in practice for IB students: the diagnostic, the learning plan, adapting to MYP criteria and DP components, review points.", cluster: D, cat: "parent-resources" },
  { key: "ib-internal-assessment-guide", kw: "IB Internal Assessment guide", lane: "The IA process across subjects: how criteria work, the timeline, academic integrity, the limits of teacher feedback, and what a tutor may and may not do.", cluster: C, cat: "dp-planning" },
  { key: "ib-mathematics-tutoring-guide", kw: "why students struggle in IB Mathematics", lane: "Root causes of struggle across AA and AI, SL and HL, and the MYP-to-DP jump; a diagnostic of struggle types with a fix for each.", cluster: M, cat: "exam-strategy", ajay: true },
  { key: "ib-university-preparation-guide", kw: "IB university preparation", lane: "How DP choices shape university applications: predicted grades, HL requirements by course, EE and TOK, Indian university equivalence via AIU, UK and US timelines.", cluster: D, cat: "dp-planning" },
  { key: "ib-exam-preparation-guide", kw: "IB exam preparation", lane: "Hub for DP exam preparation across six subjects: the May session, mocks, revision planning, paper practice, wellbeing; links to every subject and exam guide.", cluster: C, cat: "exam-strategy", pillar: true },
  { key: "best-igcse-tutors-in-gurgaon", kw: "IGCSE tutors in Gurgaon", lane: "Subject-by-subject map of IGCSE tutoring in Gurgaon: which subjects most often need support, what a specialist looks like for each, Core vs Extended, Cambridge vs Edexcel.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-south-delhi", kw: "IGCSE tutors in South Delhi", lane: "South Delhi families starting IGCSE in Class 9: choosing subjects and tiers early, the first-year habits that matter.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-noida", kw: "IGCSE tutors in Noida", lane: "Noida families facing Cambridge vs Pearson Edexcel IGCSE: how the two differ in papers and grading, what that means for tutor choice in Noida sectors.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-greater-noida", kw: "IGCSE tutors in Greater Noida", lane: "Online-first IGCSE support for Greater Noida and Greater Noida West: making online lessons work for practical-heavy subjects, when to add home sessions.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-faridabad", kw: "IGCSE tutors in Faridabad", lane: "Students switching into IGCSE from CBSE or ICSE in Faridabad: the gaps a board switch exposes and how a tutor closes them.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-dwarka-delhi", kw: "IGCSE tutors in Dwarka", lane: "IGCSE sciences (Biology 0610, Chemistry 0620, Physics 0625) for Dwarka students: practical and alternative-to-practical skills, data handling.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-vasant-kunj", kw: "IGCSE tutors in Vasant Kunj", lane: "IGCSE English (First Language and second language) and humanities for Vasant Kunj students: reading, writing, essay subjects.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-golf-course-road-gurgaon", kw: "IGCSE tutors near Golf Course Road", lane: "High-achievers along Golf Course Road: Extended Mathematics plus Additional Mathematics 0606, separate sciences, aiming at A* and preparing for DP.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-dlf-phase-5-gurgaon", kw: "IGCSE tutors in DLF Phase 5", lane: "Class 10 IGCSE students in DLF Phase 5 preparing for IB DP or A Levels next: bridge topics, subject choices, the summer after IGCSE.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-sector-56-gurgaon", kw: "IGCSE tutors in Sector 56 Gurgaon", lane: "Fitting IGCSE tuition around school, sport and activities in Sector 56: weekly schedules, session length, keeping momentum through the year.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-sushant-lok-gurgaon", kw: "IGCSE tutors in Sushant Lok", lane: "Past-paper drilling and mock recovery for Sushant Lok IGCSE students: what to do in the weeks after a weak mock.", cluster: G, cat: "local-guides" },
  { key: "igcse-tutors-delhi-ncr", kw: "IGCSE tutors in Delhi NCR", lane: "NCR geography decision guide for IGCSE: which tutoring mode suits Delhi, Gurgaon, Noida, Faridabad and Ghaziabad families, and why.", cluster: G, cat: "local-guides" },
  { key: "online-igcse-tutoring-india", kw: "online IGCSE tutoring in India", lane: "How online IGCSE tutoring works across India and for families abroad: tools, exam series timing, practical subjects online, honest limits.", cluster: I, cat: "igcse-revision" },
  { key: "personalized-home-tuition-igcse-students", kw: "personalised home tuition for IGCSE students", lane: "Personalised IGCSE home tuition as a service: the diagnostic, tier decisions, subject mix, how a tutor adapts week to week.", cluster: I, cat: "parent-resources" },
  { key: "igcse-exam-preparation-guide", kw: "IGCSE exam preparation", lane: "Hub for IGCSE exam preparation: exam series (February/March, May/June, October/November), entries, paper types, multi-subject revision; links to every IGCSE guide.", cluster: I, cat: "igcse-revision", pillar: true },
  { key: "igcse-mathematics-tutoring-guide", kw: "why students struggle in IGCSE Mathematics", lane: "Root causes of IGCSE maths struggle (algebra gaps, problem reading, calculator habits, tier mismatch) with a diagnostic and a fix for each.", cluster: I, cat: "exam-strategy", ajay: true },
  { key: "igcse-science-tutoring-guide", kw: "why students struggle in IGCSE Science", lane: "Root causes across Biology, Chemistry and Physics: command words, calculations, practical papers, recall without understanding; fixes per subject.", cluster: I, cat: "exam-strategy" },
  { key: "igcse-english-communication-skills", kw: "IGCSE English communication skills", lane: "Communication skills through IGCSE English: speaking and listening, writing for purpose and audience, First Language vs English as a Second Language.", cluster: I, cat: "igcse-revision" },
  { key: "personalized-learning-igcse-education", kw: "personalised learning in IGCSE", lane: "Personalised learning as a method a family can run without a tutor: adaptive revision, spaced retrieval, error logs, choosing tiers; when outside help adds value.", cluster: I, cat: "igcse-revision" },
  { key: "ib-gram-igcse-tutors-gurgaon-delhi-ncr", kw: "IGCSE tuition in Gurgaon and Delhi NCR", lane: "Hub for IGCSE families in Gurgaon and NCR: how IB Gram's matching, verification and trial work for IGCSE requests; links to every IGCSE area and subject guide.", cluster: G, cat: "local-guides", pillar: true },
  { key: "how-to-choose-ib-tutor-gurgaon", kw: "how to choose an IB tutor in Gurgaon", lane: "Hub parent checklist: credentials, MYP vs DP knowledge, trial lesson, red flags; links to every decision guide (fees, timing, mode, weekend, one-to-one).", cluster: D, cat: "parent-resources", pillar: true },
  { key: "ib-home-tutor-vs-online-tutor-gurgaon", kw: "IB home tutor vs online tutor in Gurgaon", lane: "Decision framework by subject and student profile: which IB subjects and students do better at home, which online, with a scoring table.", cluster: D, cat: "parent-resources" },
  { key: "ib-tutor-fees-in-gurgaon-what-affects-the-cost", old: "IB Tutor Fees in Gurgaon: What Affects the Cost?", kw: "IB tutor fees in Gurgaon", lane: "Per-session fee drivers: programme, HL vs SL, subject, tutor experience, home travel vs online, session length, packages; how to judge value. No amounts.", cluster: D, cat: "parent-resources" },
  { key: "when-to-start-ib-tutoring-gurgaon", kw: "when to start IB tutoring", lane: "Timing by stage: MYP 3-5, DP1 start, DP1 term 2, DP2; the signals that say start now, and when to wait.", cluster: D, cat: "parent-resources" },
  { key: "weekend-ib-tutoring-gurgaon", kw: "weekend IB tutoring in Gurgaon", lane: "Weekend-only schedules: one long block vs split sessions, Saturday paper practice, avoiding burnout for students with packed weekdays.", cluster: D, cat: "parent-resources" },
  { key: "ib-math-aa-hl-tutor-gurgaon-guide", kw: "IB Math AA HL tutor in Gurgaon", lane: "What parents should look for in an AA HL tutor: depth in proof, complex numbers and calculus, Paper 3 experience, IA guidance, interview questions.", cluster: M, cat: "parent-resources", ajay: true },
  { key: "ib-math-ai-hl-tutor-gurgaon-guide", kw: "IB Math AI HL tutor in Gurgaon", lane: "AI HL skills (modelling, statistics, heavy GDC use, Paper 3) and a tutor checklist specific to AI HL, including the AI exploration.", cluster: M, cat: "parent-resources", ajay: true },
  { key: "ib-math-aa-hl-paper-preparation-gurgaon", kw: "IB Math AA HL paper preparation", lane: "Paper-by-paper deep dive: question styles, timing, drills and a preparation block for each of Paper 1, Paper 2 and Paper 3.", cluster: M, cat: "exam-strategy", ajay: true },
  { key: "ib-physics-hl-tutor-gurgaon", kw: "IB Physics HL tutor in Gurgaon", lane: "Concept and paper strategy for Physics HL: themes, Paper 1 and Paper 2 demands, data and graph skills, the IA; what a tutor works on week to week.", cluster: S, cat: "exam-strategy" },
  { key: "ib-chemistry-hl-tutor-gurgaon", kw: "IB Chemistry HL tutor in Gurgaon", lane: "Chemistry HL topic gaps (structure and reactivity strands), calculations, data questions and exam preparation; what tutoring targets.", cluster: S, cat: "exam-strategy" },
  { key: "ib-biology-hl-tutor-gurgaon", kw: "IB Biology HL tutor in Gurgaon", lane: "Biology HL data-based questions, extended responses, content volume and revision; how a tutor structures it.", cluster: S, cat: "exam-strategy" },
  { key: "best-ib-maths-tutor-in-gurgaon", kw: "best IB maths tutor in Gurgaon", lane: "What 'best' means for each student profile (MYP extended, AA HL, AA SL, AI SL/HL): the evidence that separates a strong IB maths tutor; Ajay Vatsyayan's approach.", cluster: M, cat: "parent-resources", ajay: true, pillar: true },
  { key: "how-to-prepare-for-jee-advanced-mathematics-ajay-vatsyayan", old: "How to Prepare for JEE Advanced Mathematics | Ajay Vatsyayan", kw: "JEE Advanced mathematics preparation", lane: "JEE Advanced maths strategy: topic areas, multi-concept problem training, mock analysis, time strategy; and for IB students considering JEE, the overlap and gaps.", cluster: M, cat: "exam-strategy", ajay: true },
  { key: "the-gdc-advantage-in-ib-dp-mathematics-aa-hl", kw: "GDC in IB Math AA HL", lane: "Graphic display calculator techniques for AA HL Papers 2 and 3: solver, graph analysis, numerical calculus, statistics, exam mode; when the GDC hurts.", cluster: M, cat: "exam-strategy", ajay: true },
  { key: "from-igcse-mathematics-to-ib-dp-building-a-strong-foundation", kw: "IGCSE to IB DP maths transition", lane: "Gap analysis from IGCSE 0580/0606 to DP AA/AI, a summer bridge plan, choosing AA or AI after IGCSE.", cluster: M, cat: "subject-choice", ajay: true },
  { key: "ib-myp-mathematics-problem-solving-reasoning-skills", kw: "IB MYP Mathematics reasoning skills", lane: "Reasoning skills for Criterion B: investigating patterns, generalising, justifying and proving, with practice by MYP year. Not Gurgaon-specific.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "how-to-prepare-for-ib-dp-mathematics-aa-hl", kw: "how to prepare for IB Math AA HL", lane: "Two-year calendar and topic sequence for AA HL from the first week of DP1: term plans, IA timing, mocks, Year 2 run-in. Calendar, not grade-7 tactics.", cluster: M, cat: "dp-planning", ajay: true },
  { key: "how-to-choose-the-right-ib-maths-tutor-in-gurgaon", kw: "how to choose an IB maths tutor", lane: "The selection process: shortlist, interview questions, the trial lesson and what to observe, the first-month review, when to switch.", cluster: M, cat: "parent-resources", ajay: true },
  { key: "top-igcse-tutors-in-gurgaon-for-maths-science", kw: "IGCSE maths and science tutors in Gurgaon", lane: "Maths plus sciences together: one tutor or two, how 0580 and the science papers interact, weekly split, Gurgaon logistics.", cluster: G, cat: "local-guides" },
  { key: "ib-physics-hl-tutor-in-gurgaon-how-to-choose-the-right-one", kw: "how to choose an IB Physics HL tutor", lane: "Physics-specific tutor selection: checks, trial lesson tasks, red flags, how to judge explanation quality.", cluster: S, cat: "parent-resources" },
  { key: "home-vs-online-ib-tutors-in-gurgaon-what-works-better", kw: "hybrid IB tutoring in Gurgaon", lane: "Hybrid models: combining home and online across a DP year, switching mid-year, the setup each mode needs. Answers 'home vs online' with 'often both'.", cluster: D, cat: "parent-resources" },
  { key: "private-ib-tutor-cost-in-gurgaon-full-fee-breakdown", kw: "private IB tutor cost in Gurgaon", lane: "Total-programme budgeting: hours per subject per term over two DP years, when intensity peaks, building a budget without quoting amounts.", cluster: D, cat: "parent-resources" },
  { key: "1-to-1-ib-coaching-in-gurgaon-is-it-worth-it", kw: "one-to-one IB coaching in Gurgaon", lane: "Is one-to-one worth it: when it pays off vs group classes, coaching centres or self-study; a decision matrix.", cluster: D, cat: "parent-resources" },
  { key: "best-igcse-maths-tutor-near-me-in-gurgaon-sector-wise-guide", kw: "IGCSE maths tutor near me in Gurgaon", lane: "Sector-wise guide for 'near me' searchers: sector clusters (Golf Course Road, Sohna Road, New Gurgaon, Old Gurgaon, DLF phases) and home maths tuition logistics in each.", cluster: G, cat: "local-guides" },
  { key: "ib-chemistry-tutor-in-gurgaon-hl-vs-sl-support-guide", kw: "IB Chemistry HL vs SL", lane: "HL vs SL differences, choosing the level, the support each level needs, switching levels.", cluster: S, cat: "subject-choice" },
  { key: "how-to-score-a-7-in-ib-maths-aa-hl-step-by-step-strategy", kw: "IB Maths AA HL topic-by-topic strategy", lane: "Topic-by-topic playbook (number and algebra, functions, geometry and trigonometry, statistics and probability, calculus): common errors, must-drill question types, a self-test per topic. Links to the main 7 guide for the overall system.", cluster: M, cat: "exam-strategy", ajay: true },
  { key: "ib-maths-aa-vs-ai-which-one-should-you-choose", kw: "IB Maths AA vs AI", lane: "Decision guide: syllabus and assessment differences, HL vs SL, university requirements, student profiles.", cluster: M, cat: "subject-choice", ajay: true },
  { key: "complete-guide-to-ib-internal-assessment-ia-with-examples", kw: "IB IA examples", lane: "Worked examples by subject: strong vs weak research questions, structures, what lifts a criterion. Examples-led; the IA rules live in the IA guide.", cluster: C, cat: "dp-planning" },
  { key: "how-to-write-a-perfect-ib-extended-essay-ee", kw: "how to write an IB Extended Essay", lane: "The EE: research question, the reflection process, supervisor sessions, criteria, structure, timeline.", cluster: C, cat: "dp-planning" },
  { key: "ib-physics-hl-most-important-topics-study-plan", kw: "IB Physics HL study plan", lane: "Topic priorities by theme and a weekly study plan for Physics HL. Not Gurgaon-specific.", cluster: S, cat: "exam-strategy" },
  { key: "ib-chemistry-why-students-struggle-how-to-fix-it", kw: "why students struggle in IB Chemistry", lane: "Root causes (moles and stoichiometry, energetics, organic mechanisms, command terms) and fixes. Not Gurgaon-specific.", cluster: S, cat: "exam-strategy" },
  { key: "ib-exam-strategy-how-toppers-study-in-the-last-30-days", kw: "last 30 days before IB exams", lane: "The final 30 days before the May session: day-by-day structure, triage, paper rotation, sleep and logistics.", cluster: C, cat: "exam-strategy" },
  { key: "ib-command-terms-explained-with-real-examples", kw: "IB command terms", lane: "Command terms with worked examples across subjects and how they map to mark allocation.", cluster: C, cat: "exam-strategy" },
  { key: "best-igcse-maths-tutor-in-gurugram", kw: "IGCSE maths tutor in Gurugram", lane: "Quality criteria for an IGCSE maths tutor: 0580 Core/Extended, 0606, Edexcel 4MA1; what a strong tutor does in the first month.", cluster: G, cat: "local-guides", ajay: true },
  { key: "how-to-score-a-star-in-igcse-maths-0580", kw: "A* in IGCSE Maths 0580", lane: "Strategy for the top grade in Cambridge 0580 Extended: papers, high-mark topics, accuracy habits, the final term.", cluster: I, cat: "exam-strategy", ajay: true },
  { key: "igcse-maths-home-tutor-vs-coaching", kw: "IGCSE maths home tutor vs coaching", lane: "Home tutor vs coaching centre for IGCSE maths: a fair comparison, who each suits.", cluster: I, cat: "parent-resources", ajay: true },
  { key: "igcse-maths-parent-guide-0580-0606", kw: "IGCSE Maths 0580 and 0606", lane: "Parent explainer: the two syllabuses, tiers, the Additional Maths decision, how to support at home.", cluster: I, cat: "parent-resources", ajay: true },
  { key: "top-10-mistakes-in-igcse-maths", kw: "IGCSE maths mistakes", lane: "Ten specific mistakes with worked examples and the fix for each.", cluster: I, cat: "exam-strategy", ajay: true },
  { key: "igcse-maths-success-stories-from-average-to-a-star", kw: "IGCSE maths from average to A*", lane: "What the climb from a mid grade to A* typically involves, phase by phase. Uses clearly labelled illustrative profiles, never real-student stories or results.", cluster: I, cat: "exam-strategy", ajay: true },
  { key: "why-past-papers-are-key-to-igcse-maths-success", kw: "IGCSE maths past papers", lane: "Using past papers properly: when to start, how many, marking with mark schemes, examiner reports, the error log.", cluster: I, cat: "igcse-revision", ajay: true },
  { key: "online-vs-home-tutor-for-igcse-maths", kw: "online vs home tutor for IGCSE maths", lane: "Online vs home for IGCSE maths specifically: tools, writing maths online, attention, logistics, who each suits.", cluster: I, cat: "parent-resources", ajay: true },
  { key: "best-areas-in-gurugram-for-igcse-maths-home-tutors", kw: "IGCSE maths home tutors in Gurugram", lane: "Society-by-society logistics in gated communities (gate passes, study space, parent presence, evening slots) and where online is the better call.", cluster: G, cat: "local-guides" },
  { key: "3-month-study-plan-for-igcse-maths-0580", kw: "IGCSE Maths 0580 study plan", lane: "A 12-week plan for 0580: topic blocks, past-paper weeks, final fortnight. Maths only.", cluster: I, cat: "igcse-revision", ajay: true },
  { key: "ib-myp-maths-tutor-pathways-heritage-gurgaon-ajay-vatsyayan", kw: "Ajay Vatsyayan IB MYP maths tutor", lane: "Ajay Vatsyayan's approach to MYP maths for students from schools such as Pathways and Heritage: how sessions run, what parents receive, who it suits.", cluster: Y, cat: "local-guides", ajay: true },
  { key: "ib-myp-maths-tutor-gurgaon-pathways-heritage-ajay-vatsyayan", kw: "IB MYP maths tutor in Gurgaon", lane: "What MYP maths tutoring in Gurgaon covers year by year (MYP 1 to 5), standard vs extended, home and online across Gurgaon.", cluster: Y, cat: "local-guides", ajay: true },
  { key: "best-ib-myp-mathematics-tutor-pathways-heritage-gurgaon", kw: "MYP maths tutor options in Gurgaon", lane: "Comparing MYP maths tutor options (school teacher privately, coaching centre, specialist MYP tutor, online platform) with a scorecard.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "ib-myp-5-mathematics-eassessment-preparation-pathways-heritage-gurgaon", kw: "MYP 5 mathematics eAssessment preparation", lane: "The on-screen eAssessment: format, tools, how criteria appear, a preparation plan and session timing.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "ib-criterion-a-b-c-d-explained-myp-mathematics-gurgaon", kw: "MYP mathematics criteria A, B, C and D", lane: "Hub deep dive per criterion: strands, what top-band work requires, task types, common mistakes; links to every MYP guide.", cluster: Y, cat: "parent-resources", ajay: true, pillar: true },
  { key: "concept-first-ib-myp-mathematics-tutoring-pathways-heritage-gurgaon", kw: "concept-first MYP maths tutoring", lane: "Conceptual understanding: MYP key and related concepts, procedure vs concept with worked contrasts, the pay-off in DP.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "ajay-vatsyayan-sir-ib-myp-mathematics-exam-confidence-gurgaon", kw: "MYP maths exam confidence", lane: "Test anxiety and confidence: error logs, timed practice, retrieval, the parent's role.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "improve-ib-myp-mathematics-performance-gurgaon-pathways-heritage", kw: "improve IB MYP mathematics performance", lane: "A 12-week improvement plan: diagnosis, criterion targets, practice, review.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "ib-myp-mathematics-success-more-than-marks-pathways-heritage-gurgaon", kw: "MYP mathematics success beyond marks", lane: "Approaches to learning, communication, reflection and global contexts: long-term skills and how they show in DP and university.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "ib-myp-4-myp-5-mathematics-tutoring-gurgaon-pathways-heritage", kw: "MYP 4 and MYP 5 mathematics tutoring", lane: "Standard vs extended maths, the MYP 4-5 topic map, preparing for the DP AA/AI choice.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "ib-myp-mathematics-problem-solving-ajay-vatsyayan-sir-gurgaon", kw: "MYP maths problem solving", lane: "Criterion D real-life tasks and modelling, routines for unfamiliar problems, and how a tutor withdraws scaffolding to build independence.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "why-ib-myp-maths-tutor-charges-5000-per-hour", kw: "₹5,000 per hour", lane: "The economics behind premium MYP maths rates: hidden preparation and feedback hours, what a premium rate should buy, when it is not worth it.", cluster: D, cat: "parent-resources", ajay: true },
  { key: "ib-myp-maths-vs-cbse-maths-teaching-approach", kw: "IB MYP maths vs CBSE maths", lane: "Teaching approach, assessment and depth compared; switching between the two.", cluster: Y, cat: "subject-choice", ajay: true },
  { key: "how-can-an-ib-myp-maths-student-move-from-5-to-6-or-7", kw: "move from a 5 to a 7 in MYP maths", lane: "Grade-band mechanics: criterion totals behind each final grade, which criterion moves fastest, per-criterion upgrades.", cluster: Y, cat: "exam-strategy", ajay: true },
  { key: "how-to-choose-ib-maths-tutor-pathways-student-gurgaon", kw: "IB maths tutor for a Pathways student", lane: "Continuity from MYP into DP at the same school: choosing one tutor who can carry a student from MYP 4 into DP AA or AI.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "ib-myp-maths-criteria-a-b-c-d-explained-for-parents", kw: "MYP maths criteria explained for parents", lane: "Reading the report: criterion levels to final grade, what to ask the teacher, supporting each criterion at home.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "ib-maths-private-tutor-fees-india-what-parents-should-expect", kw: "IB maths private tutor fees in India", lane: "India-wide maths-specific fee guide: why fees differ by city and mode, what is included, questions to ask before paying, red flags. No amounts.", cluster: D, cat: "parent-resources", ajay: true },
  { key: "ib-maths-coaching-vs-private-tutor-myp-student", kw: "IB maths coaching vs private tutor", lane: "Coaching centre vs private tutor for an MYP student, compared fairly.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "how-to-choose-online-ib-maths-tutor-myp-students-global-guide", kw: "online IB maths tutor for MYP students", lane: "Global families: time zones, online tools, verifying an online tutor, northern and southern hemisphere school calendars.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "why-gurgaon-parents-choose-premium-private-tutors-ib-mathematics", kw: "premium private IB maths tutors in Gurgaon", lane: "Why parents pay for premium (diagnosis, continuity, criterion knowledge) and how to verify the premium is real.", cluster: D, cat: "parent-resources", ajay: true },
  { key: "how-to-choose-right-ib-myp-maths-tutor-parents-guide", kw: "how to choose the right IB MYP maths tutor", lane: "A general parent's guide for any city or online: step-by-step interview, trial and six-week review.", cluster: Y, cat: "parent-resources", ajay: true },
  { key: "why-ibgram-is-best-for-home-tuition-in-gurgaon", kw: "home tuition in Gurgaon", lane: "IB Gram's process end to end: query, matching, verification, trial, ongoing review; what families can expect and honest limits.", cluster: G, cat: "local-guides" },
  { key: "why-ib-gram-is-best-for-home-tuition-in-gurgaon", kw: "home tuition options in Gurgaon", lane: "A matching platform vs coaching centre vs word-of-mouth freelance tutor vs online marketplace: when each makes sense.", cluster: G, cat: "parent-resources" },
  { key: "how-to-choose-the-right-igcse-tutor-in-gurgaon", kw: "how to choose an IGCSE tutor in Gurgaon", lane: "Interview questions, a trial-lesson scoring rubric, red flags, when to switch.", cluster: G, cat: "parent-resources" },
  { key: "benefits-of-igcse-home-tuition-in-gurgaon", kw: "IGCSE home tuition in Gurgaon", lane: "Benefits and limits of home tuition specifically, who benefits most, honest downsides.", cluster: G, cat: "local-guides" },
  { key: "igcse-maths-home-tuition-in-gurgaon", kw: "IGCSE maths home tuition in Gurgaon", lane: "Session-by-session structure of home maths lessons for 0580 and 4MA1: weekly design, topic sequence, what the parent sees.", cluster: G, cat: "local-guides", ajay: true },
  { key: "igcse-science-home-tuition-in-gurgaon", kw: "IGCSE science home tuition in Gurgaon", lane: "Physics, Chemistry and Biology at home: practical skills without a lab, separate vs combined or co-ordinated science.", cluster: G, cat: "local-guides" },
  { key: "igcse-class-10-home-tuition-in-gurgaon", kw: "IGCSE Class 10 home tuition in Gurgaon", lane: "The Class 10 final year: mocks, series timing, multi-subject triage, revision calendar.", cluster: G, cat: "local-guides" },
  { key: "igcse-english-home-tuition-in-gurgaon", kw: "IGCSE English home tuition in Gurgaon", lane: "First Language English vs English as a Second Language vs Literature: reading and writing papers, coursework options.", cluster: G, cat: "local-guides" },
  { key: "igcse-economics-home-tuition-in-gurgaon", kw: "IGCSE Economics home tuition in Gurgaon", lane: "Economics 0455: papers, diagrams, data response, essay technique.", cluster: G, cat: "local-guides" },
  { key: "igcse-computer-science-home-tuition-in-gurgaon", kw: "IGCSE Computer Science home tuition in Gurgaon", lane: "Computer Science 0478: papers, pseudocode, algorithms, programming practice at home.", cluster: G, cat: "local-guides" },
  { key: "edexcel-igcse-mathematics-a-4ma1-higher-tier-tutor-in-gurugram-2026-guide", old: "Edexcel IGCSE Mathematics A (4MA1) Higher Tier Tutor in Gurugram: 2026 Guide", kw: "4MA1 Higher tier", lane: "4MA1 Higher tier: the two papers, grades 7-9, topics where marks are lost, a tutor's plan for Gurugram students.", cluster: G, cat: "exam-strategy", ajay: true },
];

const VOCAB = [
  "IB DP", "IB MYP", "IGCSE", "Maths AA", "Maths AI", "MYP Maths", "IGCSE Maths", "Physics", "Chemistry", "Biology",
  "English", "Economics", "Computer Science", "Gurgaon", "Delhi NCR", "Noida", "Faridabad", "South Delhi", "Home tuition",
  "Online tutoring", "Exam strategy", "Study plan", "Past papers", "Internal Assessment", "Extended Essay", "TOK", "CAS",
  "Fees", "Choosing a tutor", "Subject choice", "Cambridge", "Edexcel", "University", "JEE",
];
export const TAG_VOCAB = new Set(VOCAB);

if (process.argv[1]?.endsWith("plan.ts") && process.argv[2]) {
  const e = PLAN.find((p) => p.key === process.argv[2]);
  if (!e) throw new Error(`no plan entry ${process.argv[2]}`);
  const backup: Array<{ slug: string; title: string; body: string }> = JSON.parse(
    readFileSync("scripts/blog-rewrite/backup.json", "utf8"),
  );
  const old = backup.find((r) => r.slug === (e.old ?? e.key))!;
  console.log(
    JSON.stringify(
      {
        post: { ...e, author: e.ajay ? "Ajay Vatsyayan" : "IB Gram Editorial", output: `scripts/blog-rewrite/posts/${e.key}.md` },
        siblings: PLAN.filter((p) => p.cluster === e.cluster && p.key !== e.key).map(({ key, kw, lane }) => ({ key, kw, lane })),
        everyOtherPost: PLAN.filter((p) => p.cluster !== e.cluster).map((p) => `/blog/${p.key}/ :: ${p.kw}`),
        referencePost: `/blog/${REFERENCE}/ :: how to score a 7 in IB Math AA HL (link from every maths post)`,
        tagVocabulary: VOCAB,
        oldPost: { title: old.title, body: old.body },
      },
      null,
      1,
    ),
  );
}
