/**
 * Gurugram locality inventory for the 500-page IB/IGCSE subject x area expansion.
 *
 * `src/lib/local-seo/gurgaon/` already carries 20 areas and 71 societies with real
 * neighbour/sector/school context. Those are reused verbatim. This file adds the
 * named Gurugram localities that inventory never covered: old-city colonies, the
 * NH-48 and SPR belts, the Aravali edge and the Manesar side, so "every area of
 * Gurgaon" is genuinely every area and not just the premium corridor.
 *
 * Sectors are deliberately excluded. Sector pages already exist under
 * /ib-tutors/gurugram/sectors/ and /igcse-tutors/gurugram/sectors/.
 */
export interface AreaRow {
  name: string;
  slug: string;
  corridor: string;
  nearbyAreas: string[];
  nearbySectors: string[];
  nearbySocieties: string[];
  schools: string[];
  /** Search demand tier: drives how many pages the area gets. */
  tier: 1 | 2 | 3;
}

const S = {
  lancers: "Lancers International School",
  scottish: "Scottish High International School",
  pathways: "Pathways World School",
  goenka: "GD Goenka World School",
  shriram: "The Shri Ram School, Aravali",
  heritage: "Heritage Xperiential Learning School",
  excelsior: "Excelsior American School",
  amity: "Amity International School",
  dps: "DPS International Edge",
  suncity: "Suncity School",
  ardee: "The Ardee School",
  presidium: "Presidium School",
  matrikiran: "Matrikiran High School",
  kunskaps: "Kunskapsskolan School",
  alpha: "Alpine Convent School",
  dpsSec45: "Delhi Public School Sector 45",
  salwan: "Salwan Public School",
};

/** Localities the existing local-seo inventory never carried. */
export const NEW_AREAS: AreaRow[] = [
  {
    name: "Cyber City",
    slug: "cyber-city",
    corridor: "NH-48 and DLF Cyber City business belt",
    nearbyAreas: ["DLF Phase 2", "DLF Phase 3", "MG Road"],
    nearbySectors: ["Sector 24", "Sector 25", "Sector 26"],
    nearbySocieties: ["Ambience Caitriona", "DLF Beverly Park", "Heritage City"],
    schools: [S.lancers, S.scottish, S.amity, S.shriram, S.excelsior],
    tier: 1,
  },
  {
    name: "Sikanderpur",
    slug: "sikanderpur",
    corridor: "MG Road metro corridor",
    nearbyAreas: ["MG Road", "DLF Phase 1", "Sushant Lok 1"],
    nearbySectors: ["Sector 26", "Sector 27", "Sector 28"],
    nearbySocieties: ["DLF Beverly Park", "Heritage City", "DLF Hamilton Court"],
    schools: [S.shriram, S.heritage, S.lancers, S.amity, S.scottish],
    tier: 2,
  },
  {
    name: "Ardee City",
    slug: "ardee-city",
    corridor: "Sector 52 and Golf Course Road approach",
    nearbyAreas: ["Golf Course Road", "Sushant Lok 2", "South City 1"],
    nearbySectors: ["Sector 52", "Sector 53", "Sector 43"],
    nearbySocieties: ["DLF Park Place", "Ireo Skyon", "The Close"],
    schools: [S.ardee, S.shriram, S.heritage, S.lancers, S.pathways],
    tier: 1,
  },
  {
    name: "Rosewood City",
    slug: "rosewood-city",
    corridor: "Sector 49-50 Sohna Road belt",
    nearbyAreas: ["Sohna Road", "South City 2", "Nirvana Country"],
    nearbySectors: ["Sector 49", "Sector 50", "Sector 47"],
    nearbySocieties: ["Uppal Southend", "Orchid Petals", "Vatika City"],
    schools: [S.dpsSec45, S.suncity, S.matrikiran, S.presidium, S.goenka],
    tier: 1,
  },
  {
    name: "Uppal Southend",
    slug: "uppal-southend",
    corridor: "Sector 49 Sohna Road residential pocket",
    nearbyAreas: ["Sohna Road", "Rosewood City", "South City 2"],
    nearbySectors: ["Sector 48", "Sector 49", "Sector 50"],
    nearbySocieties: ["Rosewood City", "Orchid Petals", "Nirvana Country"],
    schools: [S.dpsSec45, S.matrikiran, S.suncity, S.goenka, S.pathways],
    tier: 2,
  },
  {
    name: "Greenwood City",
    slug: "greenwood-city",
    corridor: "Sector 45-46 central residential belt",
    nearbyAreas: ["South City 1", "Sohna Road", "Sushant Lok 1"],
    nearbySectors: ["Sector 45", "Sector 46", "Sector 40"],
    nearbySocieties: ["South City 1", "Unitech Fresco", "Malibu Towne"],
    schools: [S.dpsSec45, S.salwan, S.suncity, S.presidium, S.heritage],
    tier: 2,
  },
  {
    name: "Garden Estate",
    slug: "garden-estate",
    corridor: "MG Road and Mehrauli-Gurgaon Road edge",
    nearbyAreas: ["MG Road", "DLF Phase 1", "Sikanderpur"],
    nearbySectors: ["Sector 25", "Sector 26", "Sector 27"],
    nearbySocieties: ["Heritage City", "DLF Beverly Park", "DLF Richmond Park"],
    schools: [S.shriram, S.heritage, S.lancers, S.amity, S.scottish],
    tier: 2,
  },
  {
    name: "Ridgewood Estate",
    slug: "ridgewood-estate",
    corridor: "DLF Phase 4 central pocket",
    nearbyAreas: ["DLF Phase 4", "DLF Phase 5", "Sushant Lok 1"],
    nearbySectors: ["Sector 27", "Sector 28", "Sector 43"],
    nearbySocieties: ["DLF Hamilton Court", "DLF Regency Park", "DLF Wellington Estate"],
    schools: [S.shriram, S.lancers, S.heritage, S.scottish, S.pathways],
    tier: 2,
  },
  {
    name: "Windsor Court",
    slug: "windsor-court",
    corridor: "DLF Phase 4 and Sector 27 approach",
    nearbyAreas: ["DLF Phase 4", "Sushant Lok 1", "MG Road"],
    nearbySectors: ["Sector 27", "Sector 28", "Sector 43"],
    nearbySocieties: ["DLF Hamilton Court", "Ridgewood Estate", "DLF Regency Park"],
    schools: [S.shriram, S.lancers, S.heritage, S.amity, S.scottish],
    tier: 3,
  },
  {
    name: "Silver Oaks",
    slug: "silver-oaks",
    corridor: "DLF Phase 1 residential pocket",
    nearbyAreas: ["DLF Phase 1", "DLF Phase 2", "MG Road"],
    nearbySectors: ["Sector 26", "Sector 27", "Sector 28"],
    nearbySocieties: ["DLF Beverly Park", "DLF Richmond Park", "DLF Exclusive Floors"],
    schools: [S.lancers, S.shriram, S.scottish, S.amity, S.heritage],
    tier: 3,
  },
  {
    name: "Civil Lines",
    slug: "civil-lines",
    corridor: "Old Gurugram administrative belt",
    nearbyAreas: ["Old Gurgaon", "Sadar Bazar", "Jacobpura"],
    nearbySectors: ["Sector 14", "Sector 15", "Sector 4"],
    nearbySocieties: ["Sushant Lok 1", "South City 1", "Malibu Towne"],
    schools: [S.salwan, S.presidium, S.alpha, S.dps, S.suncity],
    tier: 2,
  },
  {
    name: "Old Gurgaon",
    slug: "old-gurgaon",
    corridor: "Old city centre around Sector 14 and Rajiv Chowk",
    nearbyAreas: ["Civil Lines", "Sadar Bazar", "Rajendra Park"],
    nearbySectors: ["Sector 14", "Sector 15", "Sector 4"],
    nearbySocieties: ["Sushant Lok 1", "Malibu Towne", "South City 1"],
    schools: [S.salwan, S.presidium, S.alpha, S.suncity, S.dps],
    tier: 2,
  },
  {
    name: "Sadar Bazar",
    slug: "sadar-bazar-gurgaon",
    corridor: "Old Gurugram market and residential core",
    nearbyAreas: ["Old Gurgaon", "Civil Lines", "Jacobpura"],
    nearbySectors: ["Sector 12", "Sector 14", "Sector 15"],
    nearbySocieties: ["South City 1", "Malibu Towne", "Sushant Lok 1"],
    schools: [S.salwan, S.alpha, S.presidium, S.suncity, S.dps],
    tier: 3,
  },
  {
    name: "Jacobpura",
    slug: "jacobpura",
    corridor: "Old Gurugram residential colony",
    nearbyAreas: ["Sadar Bazar", "Civil Lines", "Old Gurgaon"],
    nearbySectors: ["Sector 12", "Sector 14", "Sector 4"],
    nearbySocieties: ["South City 1", "Sushant Lok 1", "Malibu Towne"],
    schools: [S.salwan, S.alpha, S.presidium, S.dps, S.suncity],
    tier: 3,
  },
  {
    name: "Ashok Vihar",
    slug: "ashok-vihar-gurgaon",
    corridor: "Old Gurugram Sector 3-4 belt",
    nearbyAreas: ["Old Gurgaon", "Rajendra Park", "Palam Vihar"],
    nearbySectors: ["Sector 3", "Sector 4", "Sector 5"],
    nearbySocieties: ["Palam Vihar", "Sushant Lok 1", "South City 1"],
    schools: [S.alpha, S.salwan, S.presidium, S.dps, S.suncity],
    tier: 3,
  },
  {
    name: "Rajendra Park",
    slug: "rajendra-park",
    corridor: "West Gurugram near Old Delhi Road",
    nearbyAreas: ["Old Gurgaon", "Palam Vihar", "Basai"],
    nearbySectors: ["Sector 4", "Sector 5", "Sector 10"],
    nearbySocieties: ["Palam Vihar", "Sushant Lok 1", "Malibu Towne"],
    schools: [S.alpha, S.salwan, S.presidium, S.dps, S.suncity],
    tier: 3,
  },
  {
    name: "Basai",
    slug: "basai",
    corridor: "West Gurugram Sector 9-10 belt",
    nearbyAreas: ["Rajendra Park", "Palam Vihar", "Dwarka Expressway"],
    nearbySectors: ["Sector 9", "Sector 10", "Sector 102"],
    nearbySocieties: ["Vatika India Next", "Godrej Summit", "Sobha City"],
    schools: [S.alpha, S.dps, S.presidium, S.salwan, S.scottish],
    tier: 3,
  },
  {
    name: "Badshahpur",
    slug: "badshahpur",
    corridor: "Sohna Road and Southern Peripheral Road junction",
    nearbyAreas: ["Sohna Road", "New Gurgaon", "Nirvana Country"],
    nearbySectors: ["Sector 66", "Sector 67", "Sector 68"],
    nearbySocieties: ["Tata Primanti", "Central Park Resorts", "Vatika City"],
    schools: [S.goenka, S.matrikiran, S.pathways, S.excelsior, S.suncity],
    tier: 2,
  },
  {
    name: "Wazirabad",
    slug: "wazirabad-gurgaon",
    corridor: "Sector 52-53 Golf Course Road edge",
    nearbyAreas: ["Golf Course Road", "Ardee City", "Sushant Lok 2"],
    nearbySectors: ["Sector 52", "Sector 53", "Sector 54"],
    nearbySocieties: ["DLF Park Place", "DLF The Belaire", "Ireo Skyon"],
    schools: [S.shriram, S.ardee, S.heritage, S.lancers, S.pathways],
    tier: 3,
  },
  {
    name: "Gwal Pahari",
    slug: "gwal-pahari",
    corridor: "Gurugram-Faridabad Road Aravali belt",
    nearbyAreas: ["Golf Course Extension Road", "Ghata", "Sohna Road"],
    nearbySectors: ["Sector 55", "Sector 56", "Sector 58"],
    nearbySocieties: ["M3M Golf Estate", "Ireo Grand Arch", "Central Park Resorts"],
    schools: [S.pathways, S.shriram, S.heritage, S.goenka, S.lancers],
    tier: 2,
  },
  {
    name: "Ghata",
    slug: "ghata",
    corridor: "Sector 58-59 Aravali foothills",
    nearbyAreas: ["Golf Course Extension Road", "Gwal Pahari", "Sushant Lok 3"],
    nearbySectors: ["Sector 58", "Sector 59", "Sector 60"],
    nearbySocieties: ["M3M Golf Estate", "Ireo Grand Arch", "Central Park Resorts"],
    schools: [S.pathways, S.heritage, S.shriram, S.goenka, S.excelsior],
    tier: 3,
  },
  {
    name: "Kherki Daula",
    slug: "kherki-daula",
    corridor: "NH-48 south and Manesar approach",
    nearbyAreas: ["New Gurgaon", "Manesar", "Dwarka Expressway"],
    nearbySectors: ["Sector 84", "Sector 85", "Sector 86"],
    nearbySocieties: ["Vatika India Next", "Sobha City", "Godrej Air"],
    schools: [S.goenka, S.scottish, S.excelsior, S.dps, S.kunskaps],
    tier: 3,
  },
  {
    name: "Manesar",
    slug: "manesar",
    corridor: "IMT Manesar and NH-48 industrial-residential belt",
    nearbyAreas: ["Kherki Daula", "New Gurgaon", "Pataudi Road"],
    nearbySectors: ["Sector 82", "Sector 84", "Sector 86"],
    nearbySocieties: ["Vatika India Next", "Sobha City", "Godrej Summit"],
    schools: [S.goenka, S.scottish, S.excelsior, S.kunskaps, S.dps],
    tier: 2,
  },
  {
    name: "Pataudi Road",
    slug: "pataudi-road",
    corridor: "West Gurugram Pataudi Road growth belt",
    nearbyAreas: ["Manesar", "New Gurgaon", "Basai"],
    nearbySectors: ["Sector 88", "Sector 89", "Sector 90"],
    nearbySocieties: ["Vatika India Next", "Godrej Air", "Sobha City"],
    schools: [S.goenka, S.excelsior, S.kunskaps, S.dps, S.scottish],
    tier: 3,
  },
  {
    name: "Bhondsi",
    slug: "bhondsi",
    corridor: "Sohna Road south towards Bhondsi",
    nearbyAreas: ["Sohna Road", "Badshahpur", "New Gurgaon"],
    nearbySectors: ["Sector 68", "Sector 70", "Sector 72"],
    nearbySocieties: ["Central Park Flower Valley", "Tata Primanti", "Vatika City"],
    schools: [S.goenka, S.matrikiran, S.pathways, S.suncity, S.excelsior],
    tier: 3,
  },
  {
    name: "Sispal Vihar",
    slug: "sispal-vihar",
    corridor: "Sector 49 Sohna Road pocket",
    nearbyAreas: ["Sohna Road", "Rosewood City", "Uppal Southend"],
    nearbySectors: ["Sector 48", "Sector 49", "Sector 50"],
    nearbySocieties: ["Rosewood City", "Uppal Southend", "Orchid Petals"],
    schools: [S.dpsSec45, S.matrikiran, S.suncity, S.presidium, S.goenka],
    tier: 3,
  },
  {
    name: "Chakkarpur",
    slug: "chakkarpur",
    corridor: "Sector 28 and MG Road residential edge",
    nearbyAreas: ["MG Road", "Sushant Lok 1", "DLF Phase 4"],
    nearbySectors: ["Sector 28", "Sector 42", "Sector 43"],
    nearbySocieties: ["DLF Hamilton Court", "Heritage City", "DLF Regency Park"],
    schools: [S.shriram, S.heritage, S.lancers, S.amity, S.scottish],
    tier: 3,
  },
  {
    name: "Nathupur",
    slug: "nathupur",
    corridor: "DLF Phase 3 and Cyber City edge",
    nearbyAreas: ["DLF Phase 3", "Cyber City", "DLF Phase 2"],
    nearbySectors: ["Sector 24", "Sector 25", "Sector 26"],
    nearbySocieties: ["Ambience Caitriona", "DLF Beverly Park", "Heritage City"],
    schools: [S.lancers, S.scottish, S.amity, S.shriram, S.excelsior],
    tier: 3,
  },
  {
    name: "Southern Peripheral Road",
    slug: "southern-peripheral-road",
    corridor: "SPR linking Golf Course Extension to Sohna Road",
    nearbyAreas: ["Golf Course Extension Road", "Sohna Road", "Badshahpur"],
    nearbySectors: ["Sector 66", "Sector 67", "Sector 70"],
    nearbySocieties: ["Tata Primanti", "Central Park Resorts", "M3M Golf Estate"],
    schools: [S.pathways, S.goenka, S.matrikiran, S.excelsior, S.heritage],
    tier: 1,
  },
  {
    name: "Vatika Chowk",
    slug: "vatika-chowk",
    corridor: "Sohna Road and SPR junction",
    nearbyAreas: ["Sohna Road", "Southern Peripheral Road", "Badshahpur"],
    nearbySectors: ["Sector 48", "Sector 49", "Sector 82"],
    nearbySocieties: ["Vatika City", "Tata Primanti", "Central Park Resorts"],
    schools: [S.matrikiran, S.goenka, S.suncity, S.pathways, S.excelsior],
    tier: 3,
  },
  {
    name: "Sohna Road South",
    slug: "sohna-road-south",
    corridor: "Lower Sohna Road towards Vatika Chowk",
    nearbyAreas: ["Sohna Road", "Badshahpur", "Vatika Chowk"],
    nearbySectors: ["Sector 49", "Sector 50", "Sector 67"],
    nearbySocieties: ["Vatika City", "Orchid Petals", "Central Park Resorts"],
    schools: [S.matrikiran, S.dpsSec45, S.goenka, S.suncity, S.pathways],
    tier: 3,
  },
  {
    name: "Vipul World",
    slug: "vipul-world",
    corridor: "Sector 48 Sohna Road pocket",
    nearbyAreas: ["Sohna Road", "Nirvana Country", "South City 2"],
    nearbySectors: ["Sector 47", "Sector 48", "Sector 49"],
    nearbySocieties: ["Vipul Greens", "Vipul Belmonte", "Orchid Petals"],
    schools: [S.dpsSec45, S.matrikiran, S.suncity, S.goenka, S.presidium],
    tier: 3,
  },
  {
    name: "Ansal Esencia",
    slug: "ansal-esencia",
    corridor: "Sector 67 SPR residential township",
    nearbyAreas: ["Southern Peripheral Road", "Badshahpur", "Sohna Road"],
    nearbySectors: ["Sector 67", "Sector 68", "Sector 70"],
    nearbySocieties: ["Tata Primanti", "Central Park Resorts", "Vatika City"],
    schools: [S.goenka, S.matrikiran, S.pathways, S.excelsior, S.suncity],
    tier: 3,
  },
  {
    name: "Hero Honda Chowk",
    slug: "hero-honda-chowk",
    corridor: "NH-48 south junction and Sector 33-37 belt",
    nearbyAreas: ["New Gurgaon", "Kherki Daula", "Old Gurgaon"],
    nearbySectors: ["Sector 33", "Sector 34", "Sector 37"],
    nearbySocieties: ["Vatika India Next", "Sobha City", "Malibu Towne"],
    schools: [S.dps, S.scottish, S.goenka, S.excelsior, S.salwan],
    tier: 3,
  },
  {
    name: "IFFCO Chowk",
    slug: "iffco-chowk",
    corridor: "NH-48 and MG Road interchange",
    nearbyAreas: ["MG Road", "South City 1", "DLF Phase 2"],
    nearbySectors: ["Sector 17", "Sector 18", "Sector 29"],
    nearbySocieties: ["Heritage City", "South City 1", "DLF Beverly Park"],
    schools: [S.shriram, S.lancers, S.amity, S.salwan, S.scottish],
    tier: 3,
  },
  {
    name: "Subhash Chowk",
    slug: "subhash-chowk",
    corridor: "Sohna Road entry near Sector 32-33",
    nearbyAreas: ["Sohna Road", "South City 2", "New Gurgaon"],
    nearbySectors: ["Sector 32", "Sector 33", "Sector 47"],
    nearbySocieties: ["Malibu Towne", "Orchid Petals", "Vatika City"],
    schools: [S.dpsSec45, S.suncity, S.matrikiran, S.salwan, S.goenka],
    tier: 3,
  },
  {
    name: "Huda City Centre",
    slug: "huda-city-centre",
    corridor: "Yellow Line metro terminus and Sector 29-44 belt",
    nearbyAreas: ["South City 1", "Sushant Lok 1", "MG Road"],
    nearbySectors: ["Sector 29", "Sector 43", "Sector 44"],
    nearbySocieties: ["South City 1", "Unitech Heritage City", "Malibu Towne"],
    schools: [S.shriram, S.heritage, S.dpsSec45, S.salwan, S.suncity],
    tier: 2,
  },
  {
    name: "Rajiv Chowk",
    slug: "rajiv-chowk-gurgaon",
    corridor: "NH-48 and Sohna Road interchange",
    nearbyAreas: ["Old Gurgaon", "Sohna Road", "South City 1"],
    nearbySectors: ["Sector 32", "Sector 33", "Sector 34"],
    nearbySocieties: ["Malibu Towne", "South City 1", "Vatika City"],
    schools: [S.salwan, S.dpsSec45, S.suncity, S.presidium, S.scottish],
    tier: 3,
  },
  {
    name: "Dundahera",
    slug: "dundahera",
    corridor: "Udyog Vihar and Delhi border belt",
    nearbyAreas: ["Udyog Vihar", "DLF Phase 3", "Cyber City"],
    nearbySectors: ["Sector 19", "Sector 20", "Sector 21"],
    nearbySocieties: ["DLF Beverly Park", "Ambience Caitriona", "Heritage City"],
    schools: [S.lancers, S.scottish, S.amity, S.dps, S.excelsior],
    tier: 3,
  },
  {
    name: "Carterpuri",
    slug: "carterpuri",
    corridor: "Palam Vihar and Sector 22-23 belt",
    nearbyAreas: ["Palam Vihar", "Udyog Vihar", "Dwarka Expressway"],
    nearbySectors: ["Sector 22", "Sector 23", "Sector 21"],
    nearbySocieties: ["Godrej Summit", "Vatika India Next", "Sobha City"],
    schools: [S.dps, S.alpha, S.scottish, S.presidium, S.excelsior],
    tier: 3,
  },
];
